/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RagflowSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/folderSuggest.ts
var import_obsidian = require("obsidian");
var FolderInputSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, items, onPick) {
    super(app, inputEl);
    this.items = items;
    this.onPick = onPick;
  }
  getSuggestions(query) {
    const q = query.toLowerCase();
    return this.items().filter((path) => path.toLowerCase().includes(q));
  }
  renderSuggestion(value, el) {
    el.setText(value === "" ? "/ (root)" : value);
  }
  selectSuggestion(value) {
    this.setValue(value);
    this.onPick(value);
    this.close();
  }
};

// src/settings.ts
function normalizeFolder(value) {
  return value.trim().replace(/^\/+|\/+$/g, "");
}
var DEFAULT_SETTINGS = {
  ragflowBaseUrl: "http://127.0.0.1:9380",
  apiKey: "",
  datasetMappings: [],
  extensions: ["md", "pdf", "docx"],
  excludeGlobs: [".trash", ".obsidian"],
  internalizeLinks: false,
  normalizeTables: true,
  state: { files: {} }
};
var RagflowSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    /** RAGFlow dataset names fetched for autocomplete; empty until loaded. */
    this.ragflowDatasets = [];
    this.plugin = plugin;
  }
  /** Vault folders (plus "" for whole-vault) as picker candidates. */
  vaultFolders() {
    const paths = this.app.vault.getAllFolders(false).map((f) => f.path).sort((a, b) => a.localeCompare(b));
    return ["", ...paths];
  }
  /** Lazily fetch RAGFlow datasets for autocomplete; silent if not connected. */
  async loadRagflowDatasets() {
    const { ragflowBaseUrl, apiKey } = this.plugin.settings;
    if (!ragflowBaseUrl || !apiKey)
      return;
    try {
      this.ragflowDatasets = await this.plugin.client.listAllDatasetNames();
    } catch (_e) {
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    void this.loadRagflowDatasets();
    containerEl.createEl("h2", { text: "RAGFlow connection" });
    new import_obsidian2.Setting(containerEl).setName("RAGFlow base URL").setDesc("e.g. http://127.0.0.1:9380 (no trailing /api/v1).").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:9380").setValue(this.plugin.settings.ragflowBaseUrl).onChange(async (value) => {
        this.plugin.settings.ragflowBaseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API key").setDesc("RAGFlow API key (Bearer). Same key works for the Dataset API.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("ragflow-xxxxxxxx").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Test connection").setDesc("Verify the base URL and API key by listing RAGFlow datasets.").addButton(
      (btn) => btn.setButtonText("Test").onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Testing...");
        try {
          await this.plugin.client.listDatasets();
          new import_obsidian2.Notice("RAGFlow connection OK.");
        } catch (e) {
          new import_obsidian2.Notice(`Connection failed: ${e.message}`);
        } finally {
          btn.setDisabled(false);
          btn.setButtonText("Test");
        }
      })
    );
    containerEl.createEl("h2", { text: "Sync scope" });
    new import_obsidian2.Setting(containerEl).setName("File extensions").setDesc("Comma-separated, without dots. e.g. md,pdf,docx,pptx,txt").addText(
      (text) => text.setValue(this.plugin.settings.extensions.join(",")).onChange(async (value) => {
        this.plugin.settings.extensions = value.split(",").map((s) => s.trim().replace(/^\./, "").toLowerCase()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Exclude paths").setDesc("Comma-separated path fragments; any vault path containing one is skipped.").addText(
      (text) => text.setValue(this.plugin.settings.excludeGlobs.join(",")).onChange(async (value) => {
        this.plugin.settings.excludeGlobs = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Link internalization" });
    new import_obsidian2.Setting(containerEl).setName("Internalize Obsidian links").setDesc(
      'When syncing Markdown, rewrite [[wikilinks]] and ![[embeds]] to plain text/standard Markdown and append a "Related notes" section listing outgoing links and backlinks. Your vault files are never modified.'
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.internalizeLinks).onChange(async (value) => {
        this.plugin.settings.internalizeLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Normalize tables for RAGFlow").setDesc(
      "When syncing Markdown, rewrite tables to clean border-style Markdown \u2014 escaping stray pipes (e.g. from [[Note|alias]] links), padding columns, and adding surrounding blank lines \u2014 so RAGFlow detects and aligns them instead of mis-splitting columns. Your vault files are never modified."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.normalizeTables).onChange(async (value) => {
        this.plugin.settings.normalizeTables = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Dataset mappings" });
    containerEl.createEl("p", {
      text: "Map a vault folder to a target RAGFlow dataset (knowledge base). Every in-scope file under the folder is uploaded directly into that dataset; the note's YAML frontmatter is stripped from the upload and set as the document's RAGFlow metadata instead. Click a field to pick from existing datasets (they load after a successful Test connection); you can also type a new dataset name and it will be created on sync.",
      cls: "setting-item-description"
    });
    const listEl = containerEl.createDiv();
    this.renderMappings(listEl);
    new import_obsidian2.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("Add mapping").setCta().onClick(async () => {
        this.plugin.settings.datasetMappings.push({
          vaultPath: "",
          datasetName: ""
        });
        await this.plugin.saveSettings();
        this.renderMappings(listEl);
      })
    );
  }
  renderMappings(listEl) {
    listEl.empty();
    const mappings = this.plugin.settings.datasetMappings;
    if (mappings.length === 0) {
      listEl.createEl("p", {
        text: "No mappings yet.",
        cls: "setting-item-description"
      });
      return;
    }
    mappings.forEach((mapping, index) => {
      const row = listEl.createDiv({ cls: "ragflow-mapping-row" });
      const vaultInput = row.createEl("input", { type: "text" });
      vaultInput.placeholder = "Vault folder (e.g. Notes/Research)";
      vaultInput.value = mapping.vaultPath;
      const setVaultPath = async (value) => {
        mapping.vaultPath = normalizeFolder(value);
        await this.plugin.saveSettings();
      };
      vaultInput.addEventListener("change", () => setVaultPath(vaultInput.value));
      new FolderInputSuggest(
        this.app,
        vaultInput,
        () => this.vaultFolders(),
        (value) => void setVaultPath(value)
      );
      const arrow = row.createSpan({ text: "\u2192" });
      arrow.style.flex = "0 0 auto";
      const ragInput = row.createEl("input", { type: "text" });
      ragInput.placeholder = "RAGFlow dataset (e.g. ObsidianVault)";
      ragInput.value = mapping.datasetName;
      const setDataset = async (value) => {
        mapping.datasetName = value.trim();
        await this.plugin.saveSettings();
      };
      ragInput.addEventListener("change", () => setDataset(ragInput.value));
      new FolderInputSuggest(
        this.app,
        ragInput,
        () => this.ragflowDatasets,
        (value) => void setDataset(value)
      );
      const removeBtn = row.createEl("button", { text: "\u2715" });
      removeBtn.style.flex = "0 0 auto";
      removeBtn.addEventListener("click", async () => {
        this.plugin.settings.datasetMappings.splice(index, 1);
        await this.plugin.saveSettings();
        this.renderMappings(listEl);
      });
    });
  }
};

// src/ragflowClient.ts
var import_obsidian3 = require("obsidian");

// src/multipart.ts
function randomBoundary() {
  const rand = Array.from(
    { length: 16 },
    () => Math.floor(Math.random() * 16).toString(16)
  ).join("");
  return `----ObsidianRagflowBoundary${rand}`;
}
function concatBuffers(parts) {
  const total = parts.reduce((sum, p) => sum + p.byteLength, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.byteLength;
  }
  return out.buffer;
}
function buildMultipart(fields, files) {
  const boundary = randomBoundary();
  const encoder = new TextEncoder();
  const parts = [];
  for (const [name, value] of Object.entries(fields)) {
    parts.push(
      encoder.encode(
        `--${boundary}\r
Content-Disposition: form-data; name="${name}"\r
\r
${value}\r
`
      )
    );
  }
  for (const file of files) {
    const contentType = file.contentType ?? "application/octet-stream";
    parts.push(
      encoder.encode(
        `--${boundary}\r
Content-Disposition: form-data; name="${file.field}"; filename="${file.filename}"\r
Content-Type: ${contentType}\r
\r
`
      )
    );
    parts.push(new Uint8Array(file.data));
    parts.push(encoder.encode("\r\n"));
  }
  parts.push(encoder.encode(`--${boundary}--\r
`));
  return {
    body: concatBuffers(parts),
    contentType: `multipart/form-data; boundary=${boundary}`
  };
}

// src/ragflowClient.ts
var PAGE_SIZE = 100;
var RagflowClient = class {
  constructor(getSettings) {
    /** All datasets, listed once per client lifetime. */
    this.datasetsCache = null;
    /** dataset name -> id, resolved/created within a sync run. */
    this.datasetIdByName = /* @__PURE__ */ new Map();
    this.getSettings = getSettings;
  }
  base() {
    const url = this.getSettings().ragflowBaseUrl.replace(/\/+$/, "");
    return `${url}/api/v1`;
  }
  headers(extra) {
    return {
      Authorization: `Bearer ${this.getSettings().apiKey}`,
      ...extra
    };
  }
  async send(param) {
    const resp = await (0, import_obsidian3.requestUrl)({ ...param, throw: false });
    let payload;
    try {
      payload = resp.json;
    } catch (_e) {
      payload = void 0;
    }
    if (resp.status < 200 || resp.status >= 300) {
      const msg = payload?.message ?? resp.text ?? `HTTP ${resp.status}`;
      throw new Error(`RAGFlow error (${resp.status}): ${msg}`);
    }
    if (payload && payload.code !== void 0 && payload.code !== 0) {
      throw new Error(`RAGFlow error: ${payload.message ?? "unknown error"}`);
    }
    return payload?.data ?? payload;
  }
  query(params) {
    const parts = [];
    for (const [k, v] of Object.entries(params)) {
      if (v === void 0)
        continue;
      parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);
    }
    return parts.length ? `?${parts.join("&")}` : "";
  }
  /**
   * List every dataset, paginating fully. Memoized for the client's lifetime;
   * invalidated by this client's own dataset creates. Also used by the settings
   * tab to verify the connection (acts as a lightweight ping).
   */
  async listDatasets() {
    if (this.datasetsCache)
      return this.datasetsCache;
    const all = [];
    let page = 1;
    while (true) {
      const data = await this.send({
        url: `${this.base()}/datasets${this.query({
          page,
          page_size: PAGE_SIZE
        })}`,
        method: "GET",
        headers: this.headers()
      });
      const items = data ?? [];
      all.push(...items);
      if (items.length < PAGE_SIZE)
        break;
      page += 1;
    }
    this.datasetsCache = all;
    return all;
  }
  /** Every dataset name, sorted, for the settings dataset picker. */
  async listAllDatasetNames() {
    const datasets = await this.listDatasets();
    return datasets.map((d) => d.name).sort((a, b) => a.localeCompare(b));
  }
  async createDataset(name) {
    const dataset = await this.send({
      url: `${this.base()}/datasets`,
      method: "POST",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ name })
    });
    if (this.datasetsCache)
      this.datasetsCache.push(dataset);
    return dataset;
  }
  /**
   * Resolve a dataset id by name, creating the dataset if it does not exist.
   * Memoized per name within the client's lifetime.
   */
  async ensureDatasetId(name) {
    const trimmed = name.trim();
    if (!trimmed) {
      throw new Error("Mapping is missing a target dataset name.");
    }
    const cached = this.datasetIdByName.get(trimmed);
    if (cached)
      return cached;
    const datasets = await this.listDatasets();
    const existing = datasets.find((d) => d.name === trimmed);
    if (existing) {
      this.datasetIdByName.set(trimmed, existing.id);
      return existing.id;
    }
    try {
      const created = await this.createDataset(trimmed);
      this.datasetIdByName.set(trimmed, created.id);
      return created.id;
    } catch (e) {
      this.datasetsCache = null;
      const refreshed = await this.listDatasets();
      const found = refreshed.find((d) => d.name === trimmed);
      if (!found)
        throw e;
      this.datasetIdByName.set(trimmed, found.id);
      return found.id;
    }
  }
  /**
   * Upload one document into a dataset. RAGFlow returns the created document(s);
   * the first one's id is what we track and later attach metadata to.
   */
  async uploadDocument(datasetId, fileName, bytes, contentType) {
    const { body, contentType: ct } = buildMultipart({}, [
      { field: "file", filename: fileName, data: bytes, contentType }
    ]);
    const data = await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents`,
      method: "POST",
      headers: this.headers({ "Content-Type": ct }),
      body
    });
    const doc = Array.isArray(data) ? data[0] : data;
    if (!doc || !doc.id) {
      throw new Error(`Upload of "${fileName}" returned no document id.`);
    }
    return doc;
  }
  /**
   * Set a document's metadata (the RAGFlow "meta_fields" on Update document).
   * Replaces the document's metadata wholesale with the provided fields.
   */
  async setDocumentMetadata(datasetId, documentId, meta) {
    await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents/${documentId}`,
      method: "PUT",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ meta_fields: meta })
    });
  }
  async deleteDocuments(datasetId, ids) {
    if (ids.length === 0)
      return;
    await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents`,
      method: "DELETE",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ ids })
    });
  }
};

// src/syncState.ts
var SyncStateStore = class {
  constructor(state, save) {
    this.state = state;
    this.save = save;
  }
  getFile(vaultPath) {
    return this.state.files[vaultPath];
  }
  allFiles() {
    return this.state.files;
  }
  async setFile(vaultPath, record) {
    this.state.files[vaultPath] = record;
    await this.save();
  }
  async deleteFile(vaultPath) {
    delete this.state.files[vaultPath];
    await this.save();
  }
};

// src/syncEngine.ts
var import_obsidian4 = require("obsidian");

// src/hash.ts
async function sha256(data) {
  const digest = await crypto.subtle.digest("SHA-256", data);
  const bytes = new Uint8Array(digest);
  let hex = "";
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i].toString(16).padStart(2, "0");
  }
  return hex;
}

// src/mapping.ts
function extensionOf(path) {
  const dot = path.lastIndexOf(".");
  const slash = path.lastIndexOf("/");
  if (dot <= slash + 1)
    return "";
  return path.slice(dot + 1).toLowerCase();
}
function prefixOf(mapping) {
  return mapping.vaultPath ? `${mapping.vaultPath}/` : "";
}
function owningMapping(vaultPath, scope) {
  return scope.mappings.find((m) => {
    const prefix = prefixOf(m);
    return prefix === "" ? true : vaultPath.startsWith(prefix);
  });
}
function isInScope(vaultPath, scope) {
  if (!scope.extensions.includes(extensionOf(vaultPath)))
    return void 0;
  if (scope.excludeGlobs.some((g) => g.length > 0 && vaultPath.includes(g))) {
    return void 0;
  }
  return owningMapping(vaultPath, scope);
}

// src/diff.ts
function classifyByStat(snapshot, state, scope) {
  const result = {
    news: [],
    unchanged: [],
    needHash: [],
    deletions: [],
    reprocess: []
  };
  const inScopePaths = /* @__PURE__ */ new Set();
  for (const entry of snapshot) {
    const mapping = isInScope(entry.path, scope);
    if (!mapping)
      continue;
    inScopePaths.add(entry.path);
    const record = state.files[entry.path];
    if (!record) {
      result.news.push({ entry, mapping });
    } else if (record.processingVersion !== scope.processingVersion) {
      result.reprocess.push({ entry, record, mapping });
    } else if (record.size === entry.size && record.mtime === entry.mtime) {
      result.unchanged.push({ entry, record, mapping });
    } else {
      result.needHash.push({ entry, record, mapping });
    }
  }
  for (const [vaultPath, record] of Object.entries(state.files)) {
    if (inScopePaths.has(vaultPath))
      continue;
    result.deletions.push({
      vaultPath,
      record,
      mapping: owningMapping(vaultPath, scope)
    });
  }
  return result;
}
function finalizeWithHashes(needHash, hashes) {
  const result = {
    modified: [],
    unchanged: [],
    touches: []
  };
  for (const item of needHash) {
    const hash = hashes.get(item.entry.path);
    const base = {
      kind: "unchanged",
      vaultPath: item.entry.path,
      mapping: item.mapping,
      record: item.record,
      hash,
      size: item.entry.size,
      mtime: item.entry.mtime
    };
    if (hash !== void 0 && hash === item.record.hash) {
      result.unchanged.push(base);
      result.touches.push({
        vaultPath: item.entry.path,
        record: item.record,
        size: item.entry.size,
        mtime: item.entry.mtime
      });
    } else {
      result.modified.push({ ...base, kind: "modified" });
    }
  }
  return result;
}
function assembleChanges(stat, hashed) {
  const changes = [];
  for (const { entry, mapping } of stat.news) {
    changes.push({
      kind: "new",
      vaultPath: entry.path,
      mapping,
      size: entry.size,
      mtime: entry.mtime
    });
  }
  changes.push(...hashed.modified);
  for (const { entry, record, mapping } of stat.reprocess) {
    changes.push({
      kind: "modified",
      vaultPath: entry.path,
      mapping,
      record,
      size: entry.size,
      mtime: entry.mtime
    });
  }
  for (const { vaultPath, record, mapping } of stat.deletions) {
    changes.push({ kind: "deleted", vaultPath, mapping, record });
  }
  for (const { entry, record, mapping } of stat.unchanged) {
    changes.push({
      kind: "unchanged",
      vaultPath: entry.path,
      mapping,
      record,
      size: entry.size,
      mtime: entry.mtime
    });
  }
  changes.push(...hashed.unchanged);
  return changes;
}

// src/internalize.ts
var IMAGE_EXT = /\.(png|jpe?g|gif|svg|webp|bmp)$/i;
function parseInner(inner) {
  const pipe = inner.indexOf("|");
  const linkPart = pipe >= 0 ? inner.slice(0, pipe) : inner;
  const alias = pipe >= 0 ? inner.slice(pipe + 1).trim() : void 0;
  const hash = linkPart.indexOf("#");
  const target = (hash >= 0 ? linkPart.slice(0, hash) : linkPart).trim();
  const heading = hash >= 0 ? linkPart.slice(hash + 1).trim() : void 0;
  return { target, heading, alias: alias || void 0 };
}
function noteTitle(target) {
  const last = target.split("/").pop() ?? target;
  return last.replace(/\.md$/i, "");
}
function linkDisplay(p) {
  if (p.alias)
    return p.alias;
  if (!p.target)
    return p.heading ?? "";
  const name = noteTitle(p.target);
  return p.heading ? `${name} > ${p.heading}` : name;
}
function internalizeWikilinks(content) {
  const withEmbeds = content.replace(
    /!\[\[([^[\]]+)\]\]/g,
    (_m, inner) => {
      const p = parseInner(inner);
      if (IMAGE_EXT.test(p.target)) {
        return `![${p.alias ?? noteTitle(p.target)}](${p.target})`;
      }
      return linkDisplay(p);
    }
  );
  return withEmbeds.replace(
    /\[\[([^[\]]+)\]\]/g,
    (_m, inner) => linkDisplay(parseInner(inner))
  );
}
function stripWikilinks(text) {
  return text.replace(
    /!?\[\[([^[\]]+)\]\]/g,
    (_m, inner) => linkDisplay(parseInner(inner))
  );
}
function dedupe(titles) {
  return [...new Set(titles.filter((t) => t.length > 0))];
}
function buildRelatedSection(related) {
  const outgoing = dedupe(related.outgoing);
  const incoming = dedupe(related.incoming);
  if (outgoing.length === 0 && incoming.length === 0)
    return "";
  const lines = ["## Related notes", ""];
  if (outgoing.length > 0)
    lines.push(`**Links:** ${outgoing.join(", ")}`, "");
  if (incoming.length > 0)
    lines.push(`**Backlinks:** ${incoming.join(", ")}`, "");
  return lines.join("\n").trimEnd();
}
function internalizeMarkdown(content, related) {
  const body = internalizeWikilinks(content);
  const section = buildRelatedSection(related);
  if (!section)
    return body;
  return `${body.replace(/\s+$/, "")}

${section}
`;
}

// src/frontmatter.ts
var FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n?---[ \t]*(?:\r?\n|$)/;
function splitFrontmatter(text) {
  const match = FRONTMATTER.exec(text);
  if (!match)
    return { yaml: null, body: text };
  return { yaml: match[1] ?? "", body: text.slice(match[0].length) };
}
function cleanWikilinks(value) {
  if (typeof value === "string")
    return stripWikilinks(value);
  if (Array.isArray(value))
    return value.map(cleanWikilinks);
  if (value !== null && typeof value === "object") {
    const out = {};
    for (const [key, v] of Object.entries(value)) {
      out[key] = cleanWikilinks(v);
    }
    return out;
  }
  return value;
}
function normalizeMeta(parsed) {
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    return {};
  }
  const out = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (value === void 0)
      continue;
    out[key] = cleanWikilinks(value);
  }
  return out;
}

// src/tables.ts
var FENCE = /^\s*(```|~~~)/;
var DELIM_CELL = /^:?-+:?$/;
function splitRow(line) {
  const cells = [];
  let cur = "";
  let inCode = false;
  let bracketDepth = 0;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === "\\" && i + 1 < line.length) {
      const next = line[i + 1];
      cur += next === "|" ? "|" : "\\" + next;
      i++;
      continue;
    }
    if (ch === "`") {
      inCode = !inCode;
      cur += ch;
      continue;
    }
    if (!inCode && ch === "[" && line[i + 1] === "[") {
      bracketDepth++;
      cur += "[[";
      i++;
      continue;
    }
    if (!inCode && ch === "]" && line[i + 1] === "]" && bracketDepth > 0) {
      bracketDepth--;
      cur += "]]";
      i++;
      continue;
    }
    if (ch === "|" && !inCode && bracketDepth === 0) {
      cells.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  cells.push(cur);
  if (cells.length > 1 && cells[0].trim() === "")
    cells.shift();
  if (cells.length > 1 && cells[cells.length - 1].trim() === "")
    cells.pop();
  return cells.map((c) => c.trim());
}
function isDelimiterRow(cells) {
  return cells.length > 0 && cells.every((c) => DELIM_CELL.test(c));
}
function escapeCell(cell) {
  return cell.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|").trim();
}
function normalizeDelim(cell) {
  const left = cell.startsWith(":");
  const right = cell.endsWith(":");
  if (left && right)
    return ":---:";
  if (right)
    return "---:";
  if (left)
    return ":---";
  return "---";
}
function renderRow(cells, n) {
  const padded = cells.slice(0, n).map(escapeCell);
  while (padded.length < n)
    padded.push("");
  return `| ${padded.join(" | ")} |`;
}
function renderTable(header, delim, rows) {
  const n = header.length;
  const delimCells = delim.slice(0, n).map(normalizeDelim);
  while (delimCells.length < n)
    delimCells.push("---");
  return [
    renderRow(header, n),
    `| ${delimCells.join(" | ")} |`,
    ...rows.map((r) => renderRow(r, n))
  ].join("\n");
}
function normalizeTables(src) {
  const lines = src.split("\n");
  const out = [];
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (FENCE.test(line)) {
      inFence = !inFence;
      out.push(line);
      continue;
    }
    if (inFence) {
      out.push(line);
      continue;
    }
    const next = lines[i + 1];
    if (next !== void 0 && line.includes("|")) {
      const header = splitRow(line);
      const delim = splitRow(next);
      if (header.length >= 1 && header.length === delim.length && isDelimiterRow(delim)) {
        const rows = [];
        let j = i + 2;
        while (j < lines.length) {
          const l = lines[j];
          if (l.trim() === "" || FENCE.test(l) || !l.includes("|"))
            break;
          rows.push(splitRow(l));
          j++;
        }
        if (out.length > 0 && out[out.length - 1].trim() !== "")
          out.push("");
        out.push(renderTable(header, delim, rows));
        if (lines[j] !== void 0 && lines[j].trim() !== "")
          out.push("");
        i = j - 1;
        continue;
      }
    }
    out.push(line);
  }
  return out.join("\n");
}

// src/syncEngine.ts
var PROCESSING_VERSION = 3;
var CONTENT_TYPES = {
  md: "text/markdown",
  txt: "text/plain",
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif"
};
var SyncEngine = class {
  constructor(app, client, store, getSettings) {
    this.app = app;
    this.client = client;
    this.store = store;
    this.getSettings = getSettings;
  }
  scope() {
    const s = this.getSettings();
    return {
      mappings: s.datasetMappings,
      extensions: s.extensions,
      excludeGlobs: s.excludeGlobs,
      processingVersion: PROCESSING_VERSION
    };
  }
  /** Obsidian adapter for the vault-snapshot seam: every file, unfiltered. */
  buildSnapshot() {
    return this.app.vault.getFiles().map((f) => ({
      path: f.path,
      size: f.stat.size,
      mtime: f.stat.mtime
    }));
  }
  async hashPath(path) {
    const bytes = await this.app.vault.adapter.readBinary(path);
    return sha256(bytes);
  }
  missingMappings() {
    return this.getSettings().datasetMappings.filter(
      (m) => m.vaultPath.length > 0 && this.app.vault.getAbstractFileByPath(m.vaultPath) === null
    );
  }
  async computeDiff() {
    const state = this.getSettings().state;
    const scope = this.scope();
    const stat = classifyByStat(this.buildSnapshot(), state, scope);
    const hashes = /* @__PURE__ */ new Map();
    for (const item of stat.needHash) {
      try {
        hashes.set(item.entry.path, await this.hashPath(item.entry.path));
      } catch (_e) {
      }
    }
    const hashed = finalizeWithHashes(stat.needHash, hashes);
    for (const touch of hashed.touches) {
      await this.store.setFile(touch.vaultPath, {
        ...touch.record,
        size: touch.size,
        mtime: touch.mtime
      });
    }
    return {
      changes: assembleChanges(stat, hashed),
      missingMappings: this.missingMappings()
    };
  }
  async datasetIdFor(change) {
    if (!change.mapping) {
      throw new Error("Cannot place a file without an owning mapping.");
    }
    return this.client.ensureDatasetId(change.mapping.datasetName);
  }
  async applyChanges(changes, onProgress) {
    const actionable = changes.filter((c) => c.kind !== "unchanged");
    let done = 0;
    const result = { ok: 0, failed: 0, errors: [] };
    for (const change of actionable) {
      try {
        if (change.kind === "new") {
          await this.syncUpload(change, void 0);
        } else if (change.kind === "modified") {
          await this.syncUpload(change, change.record);
        } else if (change.kind === "deleted") {
          if (change.record) {
            await this.client.deleteDocuments(change.record.datasetId, [
              change.record.documentId
            ]);
          }
          await this.store.deleteFile(change.vaultPath);
        }
        result.ok += 1;
      } catch (e) {
        result.failed += 1;
        result.errors.push(`${change.vaultPath}: ${e.message}`);
      }
      done += 1;
      onProgress?.(done, actionable.length, change.vaultPath);
    }
    return result;
  }
  async syncUpload(change, oldRecord) {
    const file = this.app.vault.getAbstractFileByPath(change.vaultPath);
    if (!(file instanceof import_obsidian4.TFile)) {
      throw new Error("File no longer exists in vault.");
    }
    const bytes = await this.app.vault.adapter.readBinary(file.path);
    const hash = change.hash ?? await sha256(bytes);
    const datasetId = await this.datasetIdFor(change);
    if (oldRecord) {
      try {
        await this.client.deleteDocuments(oldRecord.datasetId, [
          oldRecord.documentId
        ]);
      } catch (_e) {
      }
    }
    const { uploadBytes, meta } = file.extension.toLowerCase() === "md" ? this.prepareMarkdown(bytes, file.path) : { uploadBytes: bytes, meta: {} };
    const contentType = CONTENT_TYPES[file.extension.toLowerCase()];
    const doc = await this.client.uploadDocument(
      datasetId,
      file.name,
      uploadBytes,
      contentType
    );
    if (Object.keys(meta).length > 0) {
      try {
        await this.client.setDocumentMetadata(datasetId, doc.id, meta);
      } catch (e) {
        console.error(
          `RAGFlow Sync: failed to set metadata for ${change.vaultPath}:`,
          e
        );
      }
    }
    await this.store.setFile(change.vaultPath, {
      documentId: doc.id,
      datasetId,
      hash,
      size: file.stat.size,
      mtime: file.stat.mtime,
      lastSyncedAt: Date.now(),
      processingVersion: PROCESSING_VERSION
    });
  }
  /**
   * Decode a Markdown file, strip its YAML frontmatter (parsed out as metadata),
   * optionally internalize its links and convert its tables to HTML, then
   * re-encode the body as UTF-8. The frontmatter becomes the document's RAGFlow
   * metadata rather than living in the uploaded text.
   */
  prepareMarkdown(bytes, path) {
    const text = new TextDecoder().decode(bytes);
    const { yaml, body } = splitFrontmatter(text);
    let meta = {};
    if (yaml !== null) {
      try {
        meta = normalizeMeta((0, import_obsidian4.parseYaml)(yaml));
      } catch (e) {
        console.error(`RAGFlow Sync: invalid frontmatter in ${path}:`, e);
      }
    }
    const settings = this.getSettings();
    let transformed = settings.internalizeLinks ? internalizeMarkdown(body, this.relatedLinks(path)) : body;
    if (settings.normalizeTables) {
      transformed = normalizeTables(transformed);
    }
    return {
      uploadBytes: new TextEncoder().encode(transformed).buffer,
      meta
    };
  }
  /**
   * Outgoing links and backlinks for a note, as titles, from Obsidian's
   * resolved-link graph. Only note-to-note (.md) relationships are listed;
   * attachments and unresolved links are ignored.
   */
  relatedLinks(path) {
    const resolved = this.app.metadataCache.resolvedLinks ?? {};
    const isNote = (p) => p.toLowerCase().endsWith(".md");
    const outgoing = Object.keys(resolved[path] ?? {}).filter((target) => target !== path && isNote(target)).map(noteTitle);
    const incoming = [];
    for (const [source, targets] of Object.entries(resolved)) {
      if (source !== path && isNote(source) && targets[path]) {
        incoming.push(noteTitle(source));
      }
    }
    return { outgoing, incoming };
  }
};
function summarize(changes) {
  const counts = {
    new: 0,
    modified: 0,
    deleted: 0,
    unchanged: 0
  };
  for (const c of changes)
    counts[c.kind] += 1;
  return counts;
}

// src/statusView.ts
var import_obsidian5 = require("obsidian");
var VIEW_TYPE_RAGFLOW_SYNC = "ragflow-sync-view";
var KIND_ORDER = ["new", "modified", "deleted", "unchanged"];
var KIND_LABEL = {
  new: "New",
  modified: "Modified",
  deleted: "Deleted",
  unchanged: "Up to date"
};
var RagflowSyncView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.changes = [];
    this.statusEl = null;
    this.busy = false;
    /** Vault paths the user has ticked for a manual re-upload. */
    this.selected = /* @__PURE__ */ new Set();
    /**
     * Selection mode is the manual re-upload flow: only here do per-file
     * checkboxes appear. The default (audit) view stays checkbox-free — Scan diff
     * just reports the diff and Sync all/Sync these act on it automatically.
     */
    this.selectionMode = false;
    /** The "Re-sync selected" button, kept so its label can update live. */
    this.resyncBtn = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_RAGFLOW_SYNC;
  }
  getDisplayText() {
    return "RAGFlow Sync";
  }
  getIcon() {
    return "refresh-cw";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setStatus(text) {
    if (this.statusEl)
      this.statusEl.setText(text);
  }
  async scan() {
    if (this.busy)
      return;
    if (!this.plugin.settings.apiKey) {
      new import_obsidian5.Notice("Set your RAGFlow API key in settings first.");
      return;
    }
    this.busy = true;
    this.setStatus("Scanning for differences...");
    try {
      const result = await this.plugin.engine.computeDiff();
      this.changes = result.changes;
      this.selected.clear();
      this.selectionMode = false;
      if (result.missingMappings.length > 0) {
        new import_obsidian5.Notice(
          `Some mapped folders were not found: ${result.missingMappings.map((m) => m.vaultPath).join(", ")}`
        );
      }
      this.render();
      const counts = summarize(this.changes);
      this.setStatus(
        `Scan complete: ${counts.new} new, ${counts.modified} modified, ${counts.deleted} deleted, ${counts.unchanged} up to date.`
      );
    } catch (e) {
      new import_obsidian5.Notice(`Scan failed: ${e.message}`);
      this.setStatus(`Scan failed: ${e.message}`);
    } finally {
      this.busy = false;
    }
  }
  async syncAll() {
    await this.syncChanges(this.changes);
  }
  /**
   * Re-upload exactly the files the user ticked, regardless of diff result.
   * An "unchanged" pick is promoted to "modified" (hash cleared) so the upload
   * step rebuilds RAGFlow's copy from the current source; a "deleted" pick
   * stays a deletion. Use to rebuild specific documents — e.g. ones removed or
   * left in a failed state on the RAGFlow side — without re-uploading the rest.
   */
  async syncSelected() {
    const picks = this.changes.filter((c) => this.selected.has(c.vaultPath));
    if (picks.length === 0) {
      new import_obsidian5.Notice("No files selected. Tick the files you want to re-upload.");
      return;
    }
    const forced = picks.map(
      (c) => c.kind === "unchanged" ? { ...c, kind: "modified", hash: void 0 } : c
    );
    await this.syncChanges(forced);
  }
  /**
   * Re-upload every in-scope file regardless of diff result, by promoting
   * "unchanged" entries to "modified". The command-palette "force re-sync"
   * escape hatch; the panel offers per-file selection instead.
   */
  async forceSyncAll() {
    const forced = this.changes.map(
      (c) => c.kind === "unchanged" ? { ...c, kind: "modified", hash: void 0 } : c
    );
    await this.syncChanges(forced);
  }
  async syncChanges(changes) {
    if (this.busy)
      return;
    const actionable = changes.filter((c) => c.kind !== "unchanged");
    if (actionable.length === 0) {
      new import_obsidian5.Notice("Nothing to sync.");
      return;
    }
    this.busy = true;
    try {
      const result = await this.plugin.engine.applyChanges(
        actionable,
        (done, total, label) => {
          this.setStatus(`Syncing ${done}/${total}: ${label}`);
        }
      );
      let msg = `Synced ${result.ok} item(s).`;
      if (result.failed > 0)
        msg += ` ${result.failed} failed.`;
      new import_obsidian5.Notice(msg);
      if (result.errors.length > 0) {
        console.error("RAGFlow Sync errors:", result.errors);
      }
    } catch (e) {
      new import_obsidian5.Notice(`Sync failed: ${e.message}`);
    } finally {
      this.busy = false;
      await this.scan();
    }
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ragflow-sync-view");
    this.resyncBtn = null;
    const toolbar = container.createDiv({ cls: "ragflow-sync-toolbar" });
    this.renderToolbar(toolbar);
    this.statusEl = container.createDiv({ cls: "ragflow-sync-status" });
    if (this.changes.length === 0) {
      container.createDiv({
        cls: "ragflow-sync-empty",
        text: 'No scan results yet. Click "Scan diff" to compare your vault with RAGFlow.'
      });
      return;
    }
    const byKind = /* @__PURE__ */ new Map();
    for (const kind of KIND_ORDER)
      byKind.set(kind, []);
    for (const change of this.changes)
      byKind.get(change.kind).push(change);
    for (const kind of KIND_ORDER) {
      const list = byKind.get(kind);
      if (list.length > 0)
        this.renderGroup(container, kind, list);
    }
    this.updateSelectionUi();
  }
  /**
   * The toolbar differs by mode. Audit (default): Scan diff, Sync all, and an
   * entry into selection mode. Selection: confirm the ticked re-sync, or cancel
   * back to the audit view.
   */
  renderToolbar(toolbar) {
    const scanBtn = toolbar.createEl("button", { text: "Scan diff" });
    scanBtn.onclick = () => void this.scan();
    if (this.selectionMode) {
      this.resyncBtn = toolbar.createEl("button", {
        text: "Re-sync selected"
      });
      this.resyncBtn.onclick = () => void this.syncSelected();
      const cancelBtn = toolbar.createEl("button", { text: "Cancel" });
      cancelBtn.onclick = () => {
        this.selectionMode = false;
        this.selected.clear();
        this.render();
      };
      return;
    }
    const syncAllBtn = toolbar.createEl("button", { text: "Sync all" });
    syncAllBtn.addClass("mod-cta");
    syncAllBtn.onclick = () => void this.syncChanges(this.changes);
    if (this.changes.length > 0) {
      const selectBtn = toolbar.createEl("button", {
        text: "Re-sync selected\u2026"
      });
      selectBtn.onclick = () => {
        this.selectionMode = true;
        this.selected.clear();
        this.render();
      };
    }
  }
  renderGroup(container, kind, list) {
    const group = container.createDiv({ cls: "ragflow-sync-group" });
    const header = group.createDiv({ cls: "ragflow-sync-group-header" });
    if (this.selectionMode) {
      const groupToggle = header.createEl("label", {
        cls: "ragflow-sync-group-toggle"
      });
      const groupBox = groupToggle.createEl("input", { type: "checkbox" });
      groupBox.checked = list.every((c) => this.selected.has(c.vaultPath));
      groupBox.onchange = () => {
        for (const c of list) {
          if (groupBox.checked)
            this.selected.add(c.vaultPath);
          else
            this.selected.delete(c.vaultPath);
        }
        this.render();
      };
      groupToggle.createSpan({ text: `${KIND_LABEL[kind]} (${list.length})` });
    } else {
      header.createSpan({ text: `${KIND_LABEL[kind]} (${list.length})` });
      if (kind !== "unchanged") {
        const btn = header.createEl("button", { text: "Sync these" });
        btn.onclick = () => void this.syncChanges(list);
      }
    }
    for (const change of list) {
      const item = group.createDiv({ cls: "ragflow-sync-item" });
      const main = item.createDiv({ cls: "ragflow-sync-item-main" });
      if (this.selectionMode) {
        const box = main.createEl("input", { type: "checkbox" });
        box.checked = this.selected.has(change.vaultPath);
        box.onchange = () => {
          if (box.checked)
            this.selected.add(change.vaultPath);
          else
            this.selected.delete(change.vaultPath);
          this.updateSelectionUi();
        };
      }
      main.createDiv({
        cls: "ragflow-sync-item-path",
        text: change.vaultPath
      });
      item.createSpan({
        cls: `ragflow-sync-badge ${kind}`,
        text: KIND_LABEL[kind]
      });
    }
  }
  /** Reflect the current tick count on the "Re-sync selected" button. */
  updateSelectionUi() {
    if (!this.resyncBtn)
      return;
    const n = this.selected.size;
    this.resyncBtn.setText(
      n > 0 ? `Re-sync selected (${n})` : "Re-sync selected"
    );
    this.resyncBtn.toggleClass("mod-warning", n > 0);
    this.resyncBtn.disabled = n === 0;
  }
};

// src/main.ts
var RagflowSyncPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.client = new RagflowClient(() => this.settings);
    this.store = new SyncStateStore(
      this.settings.state,
      () => this.saveSettings()
    );
    this.engine = new SyncEngine(
      this.app,
      this.client,
      this.store,
      () => this.settings
    );
    this.registerView(
      VIEW_TYPE_RAGFLOW_SYNC,
      (leaf) => new RagflowSyncView(leaf, this)
    );
    this.addRibbonIcon("refresh-cw", "RAGFlow Sync", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-ragflow-sync-panel",
      name: "Open sync panel",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "ragflow-scan-diff",
      name: "Scan for differences",
      callback: async () => {
        const view = await this.activateView();
        await view?.scan();
      }
    });
    this.addCommand({
      id: "ragflow-sync-all",
      name: "Sync all changes",
      callback: async () => {
        const view = await this.activateView();
        if (!view)
          return;
        await view.scan();
        await view.syncAll();
      }
    });
    this.addCommand({
      id: "ragflow-force-resync",
      name: "Force re-sync all (re-upload everything)",
      callback: async () => {
        const view = await this.activateView();
        if (!view)
          return;
        await view.scan();
        await view.forceSyncAll();
      }
    });
    this.addSettingTab(new RagflowSyncSettingTab(this.app, this));
  }
  onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_RAGFLOW_SYNC)[0] ?? null;
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_RAGFLOW_SYNC,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      return leaf.view;
    }
    new import_obsidian6.Notice("Could not open RAGFlow Sync panel.");
    return null;
  }
  async loadSettings() {
    const data = await this.loadData() ?? {};
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    this.settings.state = Object.assign({ files: {} }, data.state ?? {});
    this.migrateLegacyData(data);
  }
  /**
   * Migrate data.json written by the File-Management era of the plugin:
   * `folderMappings` (vault folder -> RAGFlow folder path) become
   * `datasetMappings` (vault folder -> dataset name), and any synced records
   * still keyed to File-Management files are dropped so everything re-syncs
   * into datasets on the next run.
   */
  migrateLegacyData(data) {
    const legacyMappings = data.folderMappings;
    if (legacyMappings && this.settings.datasetMappings.length === 0) {
      this.settings.datasetMappings = legacyMappings.map((m) => ({
        vaultPath: m.vaultPath ?? "",
        datasetName: m.ragflowBaseFolder ?? ""
      }));
    }
    delete this.settings.folderMappings;
    const files = this.settings.state.files;
    const isLegacyRecord = Object.values(files).some(
      (r) => r.documentId === void 0
    );
    if (isLegacyRecord) {
      this.settings.state.files = {};
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
