/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RagflowSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/folderSuggest.ts
var import_obsidian = require("obsidian");
var FolderInputSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, items, onPick) {
    super(app, inputEl);
    this.items = items;
    this.onPick = onPick;
  }
  getSuggestions(query) {
    const q = query.toLowerCase();
    return this.items().filter((path) => path.toLowerCase().includes(q));
  }
  renderSuggestion(value, el) {
    el.setText(value === "" ? "/ (root)" : value);
  }
  selectSuggestion(value) {
    this.setValue(value);
    this.onPick(value);
    this.close();
  }
};

// src/settings.ts
function normalizeFolder(value) {
  return value.trim().replace(/^\/+|\/+$/g, "");
}
var RagflowSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    /** RAGFlow dataset names fetched for autocomplete; empty until loaded. */
    this.ragflowDatasets = [];
    this.plugin = plugin;
  }
  /** Vault folders (plus "" for whole-vault) as picker candidates. */
  vaultFolders() {
    const paths = this.app.vault.getAllFolders(false).map((f) => f.path).sort((a, b) => a.localeCompare(b));
    return ["", ...paths];
  }
  /** Lazily fetch RAGFlow datasets for autocomplete; silent if not connected. */
  async loadRagflowDatasets() {
    const { ragflowBaseUrl, apiKey } = this.plugin.settings;
    if (!ragflowBaseUrl || !apiKey)
      return;
    try {
      this.ragflowDatasets = await this.plugin.client.listAllDatasetNames();
    } catch (_e) {
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    void this.loadRagflowDatasets();
    containerEl.createEl("h2", { text: "RAGFlow connection" });
    new import_obsidian2.Setting(containerEl).setName("RAGFlow base URL").setDesc("e.g. http://127.0.0.1:9380 (no trailing /api/v1).").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:9380").setValue(this.plugin.settings.ragflowBaseUrl).onChange(async (value) => {
        this.plugin.settings.ragflowBaseUrl = value.trim();
        this.plugin.client.invalidate();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API key").setDesc("RAGFlow API key (Bearer). Same key works for the Dataset API.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("ragflow-xxxxxxxx").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        this.plugin.client.invalidate();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Test connection").setDesc("Verify the base URL and API key by listing RAGFlow datasets.").addButton(
      (btn) => btn.setButtonText("Test").onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Testing...");
        try {
          this.plugin.client.invalidate();
          await this.plugin.client.listDatasets();
          new import_obsidian2.Notice("RAGFlow connection OK.");
        } catch (e) {
          new import_obsidian2.Notice(`Connection failed: ${e.message}`);
        } finally {
          btn.setDisabled(false);
          btn.setButtonText("Test");
        }
      })
    );
    containerEl.createEl("h2", { text: "Sync scope" });
    new import_obsidian2.Setting(containerEl).setName("File extensions").setDesc("Comma-separated, without dots. e.g. md,pdf,docx,pptx,txt").addText(
      (text) => text.setValue(this.plugin.settings.extensions.join(",")).onChange(async (value) => {
        this.plugin.settings.extensions = value.split(",").map((s) => s.trim().replace(/^\./, "").toLowerCase()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Exclude paths").setDesc("Comma-separated path fragments; any vault path containing one is skipped.").addText(
      (text) => text.setValue(this.plugin.settings.excludeGlobs.join(",")).onChange(async (value) => {
        this.plugin.settings.excludeGlobs = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Link internalization" });
    new import_obsidian2.Setting(containerEl).setName("Internalize Obsidian links").setDesc(
      'When syncing Markdown, rewrite [[wikilinks]] and ![[embeds]] to plain text/standard Markdown and append a "Related notes" section listing outgoing links and backlinks. Your vault files are never modified.'
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.internalizeLinks).onChange(async (value) => {
        this.plugin.settings.internalizeLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Normalize tables for RAGFlow").setDesc(
      "When syncing Markdown, rewrite tables to clean border-style Markdown \u2014 escaping stray pipes (e.g. from [[Note|alias]] links), padding columns, and adding surrounding blank lines \u2014 so RAGFlow detects and aligns them instead of mis-splitting columns. Your vault files are never modified."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.normalizeTables).onChange(async (value) => {
        this.plugin.settings.normalizeTables = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Parsing" });
    new import_obsidian2.Setting(containerEl).setName("Auto-parse after upload").setDesc(
      "After a sync uploads documents, automatically start parsing them in RAGFlow using each dataset's own configured chunking method. Turn this off to leave uploaded documents unparsed and parse them yourself in RAGFlow."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoParse).onChange(async (value) => {
        this.plugin.settings.autoParse = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Dataset mappings" });
    containerEl.createEl("p", {
      text: `Map a vault folder to a target RAGFlow dataset (knowledge base). Every in-scope file under the folder is uploaded directly into that dataset; the note's YAML frontmatter is stripped from the upload and set as the document's RAGFlow metadata instead. Click a field to pick from existing datasets (they load after a successful Test connection); you can also type a new dataset name and it will be created on sync. The "Companion meta" dropdown optionally pairs the mapping with a source folder of metadata notes \u2014 a metadata-less file (e.g. a PDF) then inherits the frontmatter of a note in that folder whose frontmatter links to it, e.g. a note with file: "[[report.pdf]]".`,
      cls: "setting-item-description"
    });
    const listEl = containerEl.createDiv();
    this.renderMappings(listEl);
    new import_obsidian2.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("Add mapping").setCta().onClick(async () => {
        this.plugin.settings.datasetMappings.push({
          vaultPath: "",
          datasetName: ""
        });
        await this.plugin.saveSettings();
        this.renderMappings(listEl);
      })
    );
  }
  renderMappings(listEl) {
    listEl.empty();
    const mappings = this.plugin.settings.datasetMappings;
    if (mappings.length === 0) {
      listEl.createEl("p", {
        text: "No mappings yet.",
        cls: "setting-item-description"
      });
      return;
    }
    mappings.forEach((mapping, index) => {
      const row = listEl.createDiv({ cls: "ragflow-mapping-row" });
      const vaultInput = row.createEl("input", { type: "text" });
      vaultInput.placeholder = "Vault folder (e.g. Notes/Research)";
      vaultInput.value = mapping.vaultPath;
      const setVaultPath = async (value) => {
        mapping.vaultPath = normalizeFolder(value);
        await this.plugin.saveSettings();
      };
      vaultInput.addEventListener("change", () => setVaultPath(vaultInput.value));
      new FolderInputSuggest(
        this.app,
        vaultInput,
        () => this.vaultFolders(),
        (value) => void setVaultPath(value)
      );
      const arrow = row.createSpan({ text: "\u2192" });
      arrow.style.flex = "0 0 auto";
      const ragInput = row.createEl("input", { type: "text" });
      ragInput.placeholder = "RAGFlow dataset (e.g. ObsidianVault)";
      ragInput.value = mapping.datasetName;
      const setDataset = async (value) => {
        mapping.datasetName = value.trim();
        await this.plugin.saveSettings();
      };
      ragInput.addEventListener("change", () => setDataset(ragInput.value));
      new FolderInputSuggest(
        this.app,
        ragInput,
        () => this.ragflowDatasets,
        (value) => void setDataset(value)
      );
      const metaSelect = row.createEl("select", {
        cls: "ragflow-mapping-meta-select"
      });
      metaSelect.title = "Companion meta source: a metadata-less file here inherits the frontmatter of a note in this folder whose frontmatter links to the file.";
      metaSelect.createEl("option", {
        text: "Companion meta: off",
        value: ""
      });
      for (const folder of this.vaultFolders()) {
        if (folder === "")
          continue;
        metaSelect.createEl("option", { text: folder, value: folder });
      }
      metaSelect.value = mapping.companionSourceFolder ?? "";
      metaSelect.addEventListener("change", async () => {
        mapping.companionSourceFolder = metaSelect.value || void 0;
        await this.plugin.saveSettings();
      });
      const removeBtn = row.createEl("button", { text: "\u2715" });
      removeBtn.style.flex = "0 0 auto";
      removeBtn.addEventListener("click", async () => {
        this.plugin.settings.datasetMappings.splice(index, 1);
        await this.plugin.saveSettings();
        this.renderMappings(listEl);
      });
    });
  }
};

// src/settingsMigration.ts
var DEFAULT_SETTINGS = {
  ragflowBaseUrl: "http://127.0.0.1:9380",
  apiKey: "",
  datasetMappings: [],
  extensions: ["md", "pdf", "docx"],
  excludeGlobs: [".trash", ".obsidian"],
  ignoredEntries: {},
  internalizeLinks: false,
  normalizeTables: true,
  autoParse: true,
  state: { files: {} }
};
function normalizeSettings(data) {
  const settings = Object.assign({}, DEFAULT_SETTINGS, data);
  settings.state = Object.assign(
    { files: {} },
    data.state ?? {}
  );
  settings.ignoredEntries = Object.assign({}, settings.ignoredEntries ?? {});
  migrateLegacyMappings(settings, data);
  removeObsoleteCompanionSettings(settings);
  dropLegacyRecords(settings);
  migrateIgnoredPaths(settings, data);
  return settings;
}
function migrateLegacyMappings(settings, data) {
  const legacyMappings = data.folderMappings;
  if (legacyMappings && settings.datasetMappings.length === 0) {
    settings.datasetMappings = legacyMappings.map((m) => ({
      vaultPath: m.vaultPath ?? "",
      datasetName: m.ragflowBaseFolder ?? ""
    }));
  }
  delete settings.folderMappings;
}
function removeObsoleteCompanionSettings(settings) {
  delete settings.companionMetadataPaths;
  for (const mapping of settings.datasetMappings) {
    delete mapping.companionMetadata;
  }
}
function dropLegacyRecords(settings) {
  const files = settings.state.files;
  const isLegacyRecord = Object.values(files).some(
    (r) => r.documentId === void 0
  );
  if (isLegacyRecord) {
    settings.state.files = {};
  }
}
function migrateIgnoredPaths(settings, data) {
  const legacyIgnored = data.ignoredPaths;
  if (Array.isArray(legacyIgnored)) {
    for (const path of legacyIgnored) {
      if (typeof path === "string" && !settings.ignoredEntries[path]) {
        settings.ignoredEntries[path] = { pending: true };
      }
    }
  }
  delete settings.ignoredPaths;
}

// src/ragflowClient.ts
var import_obsidian3 = require("obsidian");

// src/multipart.ts
function randomBoundary() {
  const rand = Array.from(
    { length: 16 },
    () => Math.floor(Math.random() * 16).toString(16)
  ).join("");
  return `----ObsidianRagflowBoundary${rand}`;
}
function concatBuffers(parts) {
  const total = parts.reduce((sum, p) => sum + p.byteLength, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.byteLength;
  }
  return out.buffer;
}
function buildMultipart(fields, files) {
  const boundary = randomBoundary();
  const encoder = new TextEncoder();
  const parts = [];
  for (const [name, value] of Object.entries(fields)) {
    parts.push(
      encoder.encode(
        `--${boundary}\r
Content-Disposition: form-data; name="${name}"\r
\r
${value}\r
`
      )
    );
  }
  for (const file of files) {
    const contentType = file.contentType ?? "application/octet-stream";
    parts.push(
      encoder.encode(
        `--${boundary}\r
Content-Disposition: form-data; name="${file.field}"; filename="${file.filename}"\r
Content-Type: ${contentType}\r
\r
`
      )
    );
    parts.push(new Uint8Array(file.data));
    parts.push(encoder.encode("\r\n"));
  }
  parts.push(encoder.encode(`--${boundary}--\r
`));
  return {
    body: concatBuffers(parts),
    contentType: `multipart/form-data; boundary=${boundary}`
  };
}

// src/ragflowClient.ts
function normalizeChunk(raw) {
  return {
    id: raw.id ?? raw.chunk_id ?? "",
    content: raw.content ?? raw.content_with_weight ?? "",
    important_keywords: raw.important_keywords ?? raw.important_kwd ?? []
  };
}
var PAGE_SIZE = 100;
function isDuplicateName(candidate, baseName) {
  const dot = baseName.lastIndexOf(".");
  const stem = dot > 0 ? baseName.slice(0, dot) : baseName;
  const ext = dot > 0 ? baseName.slice(dot) : "";
  const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${esc(stem)}(\\(\\d+\\))?${esc(ext)}$`).test(candidate);
}
var RagflowClient = class {
  constructor(getSettings) {
    /** All datasets, listed once per client lifetime. */
    this.datasetsCache = null;
    /** dataset name -> id, resolved/created within a sync run. */
    this.datasetIdByName = /* @__PURE__ */ new Map();
    this.getSettings = getSettings;
  }
  /**
   * Drop the cached dataset list and name->id map. The client lives for the
   * whole plugin session, so this must be called when the connection settings
   * (base URL / API key) change — otherwise a later list or a "Test connection"
   * would answer from a cache built against the old server.
   */
  invalidate() {
    this.datasetsCache = null;
    this.datasetIdByName.clear();
  }
  base() {
    const url = this.getSettings().ragflowBaseUrl.replace(/\/+$/, "");
    return `${url}/api/v1`;
  }
  headers(extra) {
    return {
      Authorization: `Bearer ${this.getSettings().apiKey}`,
      ...extra
    };
  }
  async send(param) {
    const resp = await (0, import_obsidian3.requestUrl)({ ...param, throw: false });
    let payload;
    try {
      payload = resp.json;
    } catch (_e) {
      payload = void 0;
    }
    if (resp.status < 200 || resp.status >= 300) {
      const msg = payload?.message ?? resp.text ?? `HTTP ${resp.status}`;
      throw new Error(`RAGFlow error (${resp.status}): ${msg}`);
    }
    if (payload && payload.code !== void 0 && payload.code !== 0) {
      throw new Error(`RAGFlow error: ${payload.message ?? "unknown error"}`);
    }
    return payload?.data ?? payload;
  }
  query(params) {
    const parts = [];
    for (const [k, v] of Object.entries(params)) {
      if (v === void 0)
        continue;
      parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);
    }
    return parts.length ? `?${parts.join("&")}` : "";
  }
  /**
   * List every dataset, paginating fully. Memoized for the client's lifetime;
   * invalidated by this client's own dataset creates. Also used by the settings
   * tab to verify the connection (acts as a lightweight ping).
   */
  async listDatasets() {
    if (this.datasetsCache)
      return this.datasetsCache;
    const all = [];
    let page = 1;
    while (true) {
      const data = await this.send({
        url: `${this.base()}/datasets${this.query({
          page,
          page_size: PAGE_SIZE
        })}`,
        method: "GET",
        headers: this.headers()
      });
      const items = data ?? [];
      all.push(...items);
      if (items.length < PAGE_SIZE)
        break;
      page += 1;
    }
    this.datasetsCache = all;
    return all;
  }
  /** Every dataset name, sorted, for the settings dataset picker. */
  async listAllDatasetNames() {
    const datasets = await this.listDatasets();
    return datasets.map((d) => d.name).sort((a, b) => a.localeCompare(b));
  }
  async createDataset(name) {
    const dataset = await this.send({
      url: `${this.base()}/datasets`,
      method: "POST",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ name })
    });
    if (this.datasetsCache)
      this.datasetsCache.push(dataset);
    return dataset;
  }
  /**
   * Resolve a dataset id by name, creating the dataset if it does not exist.
   * Memoized per name within the client's lifetime.
   */
  async ensureDatasetId(name) {
    const trimmed = name.trim();
    if (!trimmed) {
      throw new Error("Mapping is missing a target dataset name.");
    }
    const cached = this.datasetIdByName.get(trimmed);
    if (cached)
      return cached;
    const datasets = await this.listDatasets();
    const existing = datasets.find((d) => d.name === trimmed);
    if (existing) {
      this.datasetIdByName.set(trimmed, existing.id);
      return existing.id;
    }
    try {
      const created = await this.createDataset(trimmed);
      this.datasetIdByName.set(trimmed, created.id);
      return created.id;
    } catch (e) {
      this.datasetsCache = null;
      const refreshed = await this.listDatasets();
      const found = refreshed.find((d) => d.name === trimmed);
      if (!found)
        throw e;
      this.datasetIdByName.set(trimmed, found.id);
      return found.id;
    }
  }
  /**
   * Ids of documents in a dataset whose name collides with `name` — the name
   * itself plus any RAGFlow "(n)" duplicate of it (see isDuplicateName). Used to
   * clear existing copies before a re-upload so the new file replaces them
   * instead of being auto-suffixed. Narrowed server-side by keyword on the stem,
   * then matched exactly client-side; paginates fully.
   */
  async findDuplicateDocumentIds(datasetId, name) {
    const dot = name.lastIndexOf(".");
    const stem = dot > 0 ? name.slice(0, dot) : name;
    const ids = [];
    let page = 1;
    while (true) {
      const data = await this.send({
        url: `${this.base()}/datasets/${datasetId}/documents${this.query({
          keywords: stem,
          page,
          page_size: PAGE_SIZE
        })}`,
        method: "GET",
        headers: this.headers()
      });
      const docs = data?.docs ?? [];
      for (const d of docs) {
        if (d.id && isDuplicateName(d.name, name))
          ids.push(d.id);
      }
      if (docs.length < PAGE_SIZE)
        break;
      page += 1;
    }
    return ids;
  }
  /**
   * Upload one document into a dataset. RAGFlow returns the created document(s);
   * the first one's id is what we track and later attach metadata to.
   */
  async uploadDocument(datasetId, fileName, bytes, contentType) {
    const { body, contentType: ct } = buildMultipart({}, [
      { field: "file", filename: fileName, data: bytes, contentType }
    ]);
    const data = await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents`,
      method: "POST",
      headers: this.headers({ "Content-Type": ct }),
      body
    });
    const doc = Array.isArray(data) ? data[0] : data;
    if (!doc || !doc.id) {
      throw new Error(`Upload of "${fileName}" returned no document id.`);
    }
    return doc;
  }
  /**
   * Set a document's metadata (the RAGFlow "meta_fields" on Update document).
   * Replaces the document's metadata wholesale with the provided fields.
   */
  async setDocumentMetadata(datasetId, documentId, meta) {
    await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents/${documentId}`,
      method: "PUT",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ meta_fields: meta })
    });
  }
  /**
   * Start parsing the given documents in a dataset (RAGFlow "Parse documents":
   * POST /datasets/{id}/chunks). RAGFlow uses the dataset's own configured
   * chunking method; parsing then runs asynchronously on the server. Returns as
   * soon as the job is accepted, not when parsing completes.
   */
  async parseDocuments(datasetId, ids) {
    if (ids.length === 0)
      return;
    await this.send({
      url: `${this.base()}/datasets/${datasetId}/chunks`,
      method: "POST",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ document_ids: ids })
    });
  }
  /**
   * Parse status and chunk count of a single document, read from the dataset's
   * document list filtered by id. Returns undefined when the document is no
   * longer in the dataset. Used by the tag-application run to decide whether a
   * document is parsed (run === "DONE", chunk_count > 0) before tagging.
   */
  async getDocumentStatus(datasetId, documentId) {
    const data = await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents${this.query({
        id: documentId,
        page: 1,
        page_size: 1
      })}`,
      method: "GET",
      headers: this.headers()
    });
    const doc = data?.docs?.[0];
    if (!doc)
      return void 0;
    return { run: doc.run, chunkCount: doc.chunk_count ?? 0 };
  }
  /**
   * Every chunk of a parsed document, paginating fully. Chunks only exist after
   * parsing completes; an unparsed document returns an empty list. Normalized to
   * RagflowChunk so callers see a stable shape across RAGFlow versions.
   */
  async listChunks(datasetId, documentId) {
    const all = [];
    let page = 1;
    while (true) {
      const data = await this.send({
        url: `${this.base()}/datasets/${datasetId}/documents/${documentId}/chunks${this.query(
          { page, page_size: PAGE_SIZE }
        )}`,
        method: "GET",
        headers: this.headers()
      });
      const chunks = data?.chunks ?? [];
      for (const c of chunks)
        all.push(normalizeChunk(c));
      if (chunks.length < PAGE_SIZE)
        break;
      page += 1;
    }
    return all;
  }
  /**
   * Replace one chunk's important_keywords. The chunk's content is echoed back
   * unchanged because RAGFlow's Update-chunk endpoint can require it alongside
   * the keywords; sending the same content is a no-op for the body but keeps the
   * call valid across versions.
   */
  async updateChunkKeywords(datasetId, documentId, chunkId, keywords, content) {
    await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents/${documentId}/chunks/${chunkId}`,
      method: "PUT",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ content, important_keywords: keywords })
    });
  }
  async deleteDocuments(datasetId, ids) {
    if (ids.length === 0)
      return;
    await this.send({
      url: `${this.base()}/datasets/${datasetId}/documents`,
      method: "DELETE",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify({ ids })
    });
  }
};

// src/syncState.ts
var SyncStateStore = class {
  constructor(state, save) {
    this.dirty = false;
    this.state = state;
    this.save = save;
  }
  getFile(vaultPath) {
    return this.state.files[vaultPath];
  }
  allFiles() {
    return this.state.files;
  }
  /** Upsert a record in memory; call flush() to persist. */
  setFile(vaultPath, record) {
    this.state.files[vaultPath] = record;
    this.dirty = true;
  }
  /** Remove a record in memory; call flush() to persist. */
  deleteFile(vaultPath) {
    delete this.state.files[vaultPath];
    this.dirty = true;
  }
  /** Persist pending mutations, if any. A no-op when nothing changed. */
  async flush() {
    if (!this.dirty)
      return;
    this.dirty = false;
    await this.save();
  }
};

// src/hash.ts
async function sha256(data) {
  const digest = await crypto.subtle.digest("SHA-256", data);
  const bytes = new Uint8Array(digest);
  let hex = "";
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i].toString(16).padStart(2, "0");
  }
  return hex;
}

// src/mapping.ts
function extensionOf(path) {
  const dot = path.lastIndexOf(".");
  const slash = path.lastIndexOf("/");
  if (dot <= slash + 1)
    return "";
  return path.slice(dot + 1).toLowerCase();
}
function prefixOf(mapping) {
  return mapping.vaultPath ? `${mapping.vaultPath}/` : "";
}
function owningMapping(vaultPath, scope) {
  return scope.mappings.find((m) => {
    const prefix = prefixOf(m);
    return prefix === "" ? true : vaultPath.startsWith(prefix);
  });
}
function isInScope(vaultPath, scope) {
  if (!scope.extensions.includes(extensionOf(vaultPath)))
    return void 0;
  if (scope.excludeGlobs.some((g) => g.length > 0 && vaultPath.includes(g))) {
    return void 0;
  }
  return owningMapping(vaultPath, scope);
}

// src/diff.ts
function classifyByStat(snapshot, state, scope) {
  const result = {
    news: [],
    unchanged: [],
    needHash: [],
    deletions: [],
    reprocess: []
  };
  const inScopePaths = /* @__PURE__ */ new Set();
  for (const entry of snapshot) {
    const mapping = isInScope(entry.path, scope);
    if (!mapping)
      continue;
    inScopePaths.add(entry.path);
    const record = state.files[entry.path];
    if (!record) {
      result.news.push({ entry, mapping });
    } else if (record.processingVersion !== scope.processingVersion) {
      result.reprocess.push({ entry, record, mapping });
    } else if (record.metaPending) {
      result.reprocess.push({ entry, record, mapping });
    } else if (record.size === entry.size && record.mtime === entry.mtime) {
      result.unchanged.push({ entry, record, mapping });
    } else {
      result.needHash.push({ entry, record, mapping });
    }
  }
  for (const [vaultPath, record] of Object.entries(state.files)) {
    if (inScopePaths.has(vaultPath))
      continue;
    result.deletions.push({
      vaultPath,
      record,
      mapping: owningMapping(vaultPath, scope)
    });
  }
  return result;
}
function finalizeWithHashes(needHash, hashes) {
  const result = {
    modified: [],
    unchanged: [],
    touches: []
  };
  for (const item of needHash) {
    const hash = hashes.get(item.entry.path);
    const base = {
      kind: "unchanged",
      vaultPath: item.entry.path,
      mapping: item.mapping,
      record: item.record,
      hash,
      size: item.entry.size,
      mtime: item.entry.mtime
    };
    if (hash !== void 0 && hash === item.record.hash) {
      result.unchanged.push(base);
      result.touches.push({
        vaultPath: item.entry.path,
        record: item.record,
        size: item.entry.size,
        mtime: item.entry.mtime
      });
    } else {
      result.modified.push({ ...base, kind: "modified" });
    }
  }
  return result;
}
function assembleChanges(stat, hashed) {
  const changes = [];
  for (const { entry, mapping } of stat.news) {
    changes.push({
      kind: "new",
      vaultPath: entry.path,
      mapping,
      size: entry.size,
      mtime: entry.mtime
    });
  }
  changes.push(...hashed.modified);
  for (const { entry, record, mapping } of stat.reprocess) {
    changes.push({
      kind: "modified",
      vaultPath: entry.path,
      mapping,
      record,
      size: entry.size,
      mtime: entry.mtime
    });
  }
  for (const { vaultPath, record, mapping } of stat.deletions) {
    changes.push({ kind: "deleted", vaultPath, mapping, record });
  }
  for (const { entry, record, mapping } of stat.unchanged) {
    changes.push({
      kind: "unchanged",
      vaultPath: entry.path,
      mapping,
      record,
      size: entry.size,
      mtime: entry.mtime
    });
  }
  changes.push(...hashed.unchanged);
  return changes;
}
function markIgnored(changes, ignoredEntries, currentHashes) {
  const staleIgnores = [];
  const captured = {};
  for (const change of changes) {
    const snap = ignoredEntries[change.vaultPath];
    if (!snap)
      continue;
    const hashNow = change.hash ?? currentHashes.get(change.vaultPath);
    if ("deleted" in snap) {
      if (change.kind === "deleted")
        change.ignored = true;
      else
        staleIgnores.push(change.vaultPath);
      continue;
    }
    if ("pending" in snap) {
      change.ignored = true;
      if (change.kind === "deleted") {
        captured[change.vaultPath] = { deleted: true };
      } else if (hashNow !== void 0 && change.size !== void 0 && change.mtime !== void 0) {
        captured[change.vaultPath] = {
          hash: hashNow,
          size: change.size,
          mtime: change.mtime
        };
      }
      continue;
    }
    if (change.kind === "deleted") {
      staleIgnores.push(change.vaultPath);
      continue;
    }
    if (change.size === snap.size && change.mtime === snap.mtime) {
      change.ignored = true;
    } else if (hashNow !== void 0 && hashNow === snap.hash) {
      change.ignored = true;
      captured[change.vaultPath] = {
        hash: snap.hash,
        size: change.size ?? snap.size,
        mtime: change.mtime ?? snap.mtime
      };
    } else {
      staleIgnores.push(change.vaultPath);
    }
  }
  return { changes, staleIgnores, captured };
}

// src/syncApplyRun.ts
var import_obsidian4 = require("obsidian");

// src/internalize.ts
var IMAGE_EXT = /\.(png|jpe?g|gif|svg|webp|bmp)$/i;
function parseInner(inner) {
  const pipe = inner.indexOf("|");
  const linkPart = pipe >= 0 ? inner.slice(0, pipe) : inner;
  const alias = pipe >= 0 ? inner.slice(pipe + 1).trim() : void 0;
  const hash = linkPart.indexOf("#");
  const target = (hash >= 0 ? linkPart.slice(0, hash) : linkPart).trim();
  const heading = hash >= 0 ? linkPart.slice(hash + 1).trim() : void 0;
  return { target, heading, alias: alias || void 0 };
}
function noteTitle(target) {
  const last = target.split("/").pop() ?? target;
  return last.replace(/\.md$/i, "");
}
function linkDisplay(p) {
  if (p.alias)
    return p.alias;
  if (!p.target)
    return p.heading ?? "";
  const name = noteTitle(p.target);
  return p.heading ? `${name} > ${p.heading}` : name;
}
function internalizeWikilinks(content) {
  const withEmbeds = content.replace(
    /!\[\[([^[\]]+)\]\]/g,
    (_m, inner) => {
      const p = parseInner(inner);
      if (IMAGE_EXT.test(p.target)) {
        return `![${p.alias ?? noteTitle(p.target)}](${p.target})`;
      }
      return linkDisplay(p);
    }
  );
  return withEmbeds.replace(
    /\[\[([^[\]]+)\]\]/g,
    (_m, inner) => linkDisplay(parseInner(inner))
  );
}
function stripWikilinks(text) {
  return text.replace(
    /!?\[\[([^[\]]+)\]\]/g,
    (_m, inner) => linkDisplay(parseInner(inner))
  );
}
function dedupe(titles) {
  return [...new Set(titles.filter((t) => t.length > 0))];
}
function buildRelatedSection(related) {
  const outgoing = dedupe(related.outgoing);
  const incoming = dedupe(related.incoming);
  if (outgoing.length === 0 && incoming.length === 0)
    return "";
  const lines = ["## Related notes", ""];
  if (outgoing.length > 0)
    lines.push(`**Links:** ${outgoing.join(", ")}`, "");
  if (incoming.length > 0)
    lines.push(`**Backlinks:** ${incoming.join(", ")}`, "");
  return lines.join("\n").trimEnd();
}
function internalizeMarkdown(content, related) {
  const body = internalizeWikilinks(content);
  const section = buildRelatedSection(related);
  if (!section)
    return body;
  return `${body.replace(/\s+$/, "")}

${section}
`;
}

// src/frontmatter.ts
var FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n?---[ \t]*(?:\r?\n|$)/;
function splitFrontmatter(text) {
  const match = FRONTMATTER.exec(text);
  if (!match)
    return { yaml: null, body: text };
  return { yaml: match[1] ?? "", body: text.slice(match[0].length) };
}
function cleanWikilinks(value) {
  if (typeof value === "string")
    return stripWikilinks(value);
  if (value instanceof Date)
    return isoDate(value);
  if (Array.isArray(value))
    return value.map(cleanWikilinks);
  if (value !== null && typeof value === "object") {
    const out = {};
    for (const [key, v] of Object.entries(value)) {
      out[key] = cleanWikilinks(v);
    }
    return out;
  }
  return value;
}
function isoDate(d) {
  const iso = d.toISOString();
  return iso.endsWith("T00:00:00.000Z") ? iso.slice(0, 10) : iso;
}
function metaValue(value) {
  if (value === null || value === void 0)
    return void 0;
  if (typeof value === "string")
    return stripWikilinks(value);
  if (typeof value === "boolean")
    return value;
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : void 0;
  }
  if (value instanceof Date)
    return isoDate(value);
  if (Array.isArray(value)) {
    return value.map(metaValue).filter((v) => v !== void 0).map((v) => typeof v === "object" ? JSON.stringify(v) : v);
  }
  if (typeof value === "object") {
    return JSON.stringify(cleanWikilinks(value));
  }
  return void 0;
}
function frontmatterLinkTargets(value) {
  const out = [];
  const visit = (v) => {
    if (typeof v === "string") {
      const re = /\[\[([^[\]]+)\]\]/g;
      let m;
      while ((m = re.exec(v)) !== null) {
        const path = m[1].split("|")[0].split("#")[0].trim();
        if (path)
          out.push(path);
      }
    } else if (Array.isArray(v)) {
      v.forEach(visit);
    } else if (v !== null && typeof v === "object") {
      Object.values(v).forEach(visit);
    }
  };
  visit(value);
  return out;
}
function splitPartStem(baseName) {
  const m = /^(.+?)_p\d+(?:-\d+)?$/i.exec(baseName);
  return m ? m[1] : null;
}
function normalizeMeta(parsed) {
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed) || parsed instanceof Date) {
    return {};
  }
  const out = {};
  for (const [key, value] of Object.entries(parsed)) {
    const v = metaValue(value);
    if (v === void 0)
      continue;
    out[key] = v;
  }
  return out;
}

// src/tables.ts
var FENCE = /^\s*(```|~~~)/;
var DELIM_CELL = /^:?-+:?$/;
function splitRow(line) {
  const cells = [];
  let cur = "";
  let inCode = false;
  let bracketDepth = 0;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === "\\" && i + 1 < line.length) {
      const next = line[i + 1];
      cur += next === "|" ? "|" : "\\" + next;
      i++;
      continue;
    }
    if (ch === "`") {
      inCode = !inCode;
      cur += ch;
      continue;
    }
    if (!inCode && ch === "[" && line[i + 1] === "[") {
      bracketDepth++;
      cur += "[[";
      i++;
      continue;
    }
    if (!inCode && ch === "]" && line[i + 1] === "]" && bracketDepth > 0) {
      bracketDepth--;
      cur += "]]";
      i++;
      continue;
    }
    if (ch === "|" && !inCode && bracketDepth === 0) {
      cells.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  cells.push(cur);
  if (cells.length > 1 && cells[0].trim() === "")
    cells.shift();
  if (cells.length > 1 && cells[cells.length - 1].trim() === "")
    cells.pop();
  return cells.map((c) => c.trim());
}
function isDelimiterRow(cells) {
  return cells.length > 0 && cells.every((c) => DELIM_CELL.test(c));
}
function escapeCell(cell) {
  return cell.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|").trim();
}
function normalizeDelim(cell) {
  const left = cell.startsWith(":");
  const right = cell.endsWith(":");
  if (left && right)
    return ":---:";
  if (right)
    return "---:";
  if (left)
    return ":---";
  return "---";
}
function renderRow(cells, n) {
  const padded = cells.slice(0, n).map(escapeCell);
  while (padded.length < n)
    padded.push("");
  return `| ${padded.join(" | ")} |`;
}
function renderTable(header, delim, rows) {
  const n = header.length;
  const delimCells = delim.slice(0, n).map(normalizeDelim);
  while (delimCells.length < n)
    delimCells.push("---");
  return [
    renderRow(header, n),
    `| ${delimCells.join(" | ")} |`,
    ...rows.map((r) => renderRow(r, n))
  ].join("\n");
}
function normalizeTables(src) {
  const lines = src.split("\n");
  const out = [];
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (FENCE.test(line)) {
      inFence = !inFence;
      out.push(line);
      continue;
    }
    if (inFence) {
      out.push(line);
      continue;
    }
    const next = lines[i + 1];
    if (next !== void 0 && line.includes("|")) {
      const header = splitRow(line);
      const delim = splitRow(next);
      if (header.length >= 1 && header.length === delim.length && isDelimiterRow(delim)) {
        const rows = [];
        let j = i + 2;
        while (j < lines.length) {
          const l = lines[j];
          if (l.trim() === "" || FENCE.test(l) || !l.includes("|"))
            break;
          rows.push(splitRow(l));
          j++;
        }
        if (out.length > 0 && out[out.length - 1].trim() !== "")
          out.push("");
        out.push(renderTable(header, delim, rows));
        if (lines[j] !== void 0 && lines[j].trim() !== "")
          out.push("");
        i = j - 1;
        continue;
      }
    }
    out.push(line);
  }
  return out.join("\n");
}

// src/companionMetadata.ts
async function buildCompanionIndex(settings, vault) {
  const index = /* @__PURE__ */ new Map();
  const folders = new Set(
    settings.datasetMappings.map((m) => m.companionSourceFolder).filter((f) => !!f && f.length > 0)
  );
  for (const folder of folders) {
    const map = /* @__PURE__ */ new Map();
    for (const note of vault.markdownFilesUnder(folder)) {
      const fm = await vault.frontmatter(note);
      if (!fm)
        continue;
      const targets = frontmatterLinkTargets(fm);
      if (targets.length === 0)
        continue;
      const meta = normalizeMeta(fm);
      for (const target of targets) {
        indexCompanionTarget(map, vault, note, target, meta);
      }
    }
    index.set(folder, map);
  }
  return index;
}
function indexCompanionTarget(map, vault, note, linkpath, meta) {
  const dest = vault.resolveLink(linkpath, note.path);
  if (dest)
    map.set(dest.path, meta);
  const name = (linkpath.split("/").pop() ?? linkpath).trim();
  if (!name)
    return;
  map.set(`name:${name.toLowerCase()}`, meta);
  const dot = name.lastIndexOf(".");
  const base = dot > 0 ? name.slice(0, dot) : name;
  map.set(`base:${base.toLowerCase()}`, meta);
}
function lookupCompanion(companionIndex, sourceFolder, file) {
  const map = companionIndex.get(sourceFolder);
  if (!map)
    return void 0;
  const direct = map.get(file.path) ?? map.get(`name:${file.name.toLowerCase()}`) ?? map.get(`base:${file.basename.toLowerCase()}`);
  if (direct)
    return direct;
  const stem = splitPartStem(file.basename);
  return stem ? map.get(`base:${stem.toLowerCase()}`) : void 0;
}

// src/syncApplyRun.ts
var PROCESSING_VERSION = 4;
var CONTENT_TYPES = {
  md: "text/markdown",
  txt: "text/plain",
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif"
};
var FLUSH_EVERY = 25;
async function applySyncRun(input) {
  const run = new SyncApplyRun(input);
  return run.apply();
}
var SyncApplyRun = class {
  constructor(input) {
    this.vault = input.vault;
    this.client = input.client;
    this.store = input.store;
    this.settings = input.settings;
    this.changes = input.changes;
    this.onProgress = input.onProgress;
    this.processingVersion = input.processingVersion ?? PROCESSING_VERSION;
  }
  async apply() {
    const actionable = this.changes.filter((c) => c.kind !== "unchanged");
    let done = 0;
    const result = { ok: 0, failed: 0, errors: [], parsed: 0 };
    const uploaded = /* @__PURE__ */ new Map();
    const companionIndex = await buildCompanionIndex(this.settings, this.vault);
    let sinceFlush = 0;
    try {
      for (const change of actionable) {
        try {
          if (change.kind === "new") {
            const up = await this.syncUpload(change, void 0, companionIndex);
            this.recordUpload(uploaded, up);
            if (up.error)
              throw up.error;
          } else if (change.kind === "modified") {
            const up = await this.syncUpload(
              change,
              change.record,
              companionIndex
            );
            this.recordUpload(uploaded, up);
            if (up.error)
              throw up.error;
          } else if (change.kind === "deleted") {
            await this.syncDelete(change);
          }
          result.ok += 1;
        } catch (e) {
          result.failed += 1;
          result.errors.push(`${change.vaultPath}: ${e.message}`);
        }
        done += 1;
        if (++sinceFlush >= FLUSH_EVERY) {
          await this.store.flush();
          sinceFlush = 0;
        }
        this.onProgress?.(done, actionable.length, change.vaultPath);
      }
    } finally {
      await this.store.flush();
    }
    if (this.settings.autoParse) {
      await this.parseUploaded(uploaded, done, actionable.length, result);
    }
    return result;
  }
  async syncDelete(change) {
    if (change.record) {
      try {
        await this.client.deleteDocuments(change.record.datasetId, [
          change.record.documentId
        ]);
      } catch (e) {
        console.warn(
          `RAGFlow Sync: delete of ${change.vaultPath} failed (treating as already gone): ${e.message}`
        );
      }
    }
    this.store.deleteFile(change.vaultPath);
  }
  async parseUploaded(uploaded, done, total, result) {
    for (const [datasetId, ids] of uploaded) {
      this.onProgress?.(done, total, `Parsing ${ids.length} document(s)...`);
      try {
        await this.client.parseDocuments(datasetId, ids);
        result.parsed += ids.length;
      } catch (e) {
        result.errors.push(
          `parse (dataset ${datasetId}): ${e.message}`
        );
      }
    }
  }
  recordUpload(uploaded, up) {
    const ids = uploaded.get(up.datasetId);
    if (ids)
      ids.push(up.documentId);
    else
      uploaded.set(up.datasetId, [up.documentId]);
  }
  async syncUpload(change, oldRecord, companionIndex) {
    const file = this.vault.getFile(change.vaultPath);
    if (!file) {
      throw new Error("File no longer exists in vault.");
    }
    const bytes = await this.vault.readBinary(file.path);
    const hash = change.hash ?? await sha256(bytes);
    const datasetId = await this.datasetIdFor(change);
    if (oldRecord) {
      try {
        await this.client.deleteDocuments(oldRecord.datasetId, [
          oldRecord.documentId
        ]);
      } catch (_e) {
      }
    }
    await this.clearDuplicateDocuments(datasetId, file.name);
    const prepared = file.extension.toLowerCase() === "md" ? this.prepareMarkdown(bytes, file.path) : { uploadBytes: bytes, meta: {} };
    const uploadBytes = prepared.uploadBytes;
    let meta = prepared.meta;
    const sourceFolder = change.mapping?.companionSourceFolder;
    if (Object.keys(meta).length === 0 && sourceFolder) {
      const found = lookupCompanion(companionIndex, sourceFolder, file);
      if (found) {
        meta = found;
      } else {
        console.warn(
          `RAGFlow Sync: no companion metadata for ${change.vaultPath} - no note in "${sourceFolder}" has a frontmatter link to it, so the document is uploaded without metadata.`
        );
      }
    }
    const contentType = CONTENT_TYPES[file.extension.toLowerCase()];
    const doc = await this.client.uploadDocument(
      datasetId,
      file.name,
      uploadBytes,
      contentType
    );
    let metaError = null;
    if (Object.keys(meta).length > 0) {
      try {
        await this.client.setDocumentMetadata(datasetId, doc.id, meta);
      } catch (e) {
        metaError = e;
        console.error(
          `RAGFlow Sync: failed to set metadata for ${change.vaultPath}:`,
          e,
          "\nmeta_fields sent:",
          JSON.stringify(meta)
        );
      }
    }
    this.store.setFile(change.vaultPath, {
      documentId: doc.id,
      datasetId,
      hash,
      size: file.stat.size,
      mtime: file.stat.mtime,
      lastSyncedAt: Date.now(),
      processingVersion: this.processingVersion,
      ...metaError ? { metaPending: true } : {}
    });
    delete this.settings.ignoredEntries[change.vaultPath];
    return {
      datasetId,
      documentId: doc.id,
      ...metaError ? {
        error: new Error(
          `uploaded, but setting metadata failed: ${metaError.message} (document kept; metadata will be retried on the next scan)`
        )
      } : {}
    };
  }
  async clearDuplicateDocuments(datasetId, name) {
    try {
      const dupes = await this.client.findDuplicateDocumentIds(datasetId, name);
      if (dupes.length > 0) {
        await this.client.deleteDocuments(datasetId, dupes);
      }
    } catch (e) {
      console.warn(
        `RAGFlow Sync: could not clear duplicates of ${name} before upload: ${e.message}`
      );
    }
  }
  async datasetIdFor(change) {
    if (!change.mapping) {
      throw new Error("Cannot place a file without an owning mapping.");
    }
    return this.client.ensureDatasetId(change.mapping.datasetName);
  }
  prepareMarkdown(bytes, path) {
    const text = new TextDecoder().decode(bytes);
    const { yaml, body } = splitFrontmatter(text);
    let meta = {};
    if (yaml !== null) {
      try {
        meta = normalizeMeta((0, import_obsidian4.parseYaml)(yaml));
      } catch (e) {
        console.error(`RAGFlow Sync: invalid frontmatter in ${path}:`, e);
      }
    }
    let transformed = this.settings.internalizeLinks ? internalizeMarkdown(body, this.vault.relatedLinks(path)) : body;
    if (this.settings.normalizeTables) {
      transformed = normalizeTables(transformed);
    }
    return {
      uploadBytes: new TextEncoder().encode(transformed).buffer,
      meta
    };
  }
};

// src/noteTags.ts
function noteTags(tagsValue) {
  const out = [];
  const push = (raw) => {
    for (const piece of raw.split(/[\s,]+/)) {
      const tag = piece.replace(/^#+/, "").trim();
      if (tag)
        out.push(tag);
    }
  };
  const visit = (v) => {
    if (v === null || v === void 0)
      return;
    if (Array.isArray(v)) {
      v.forEach(visit);
    } else if (typeof v === "string") {
      push(v);
    } else if (typeof v === "number" || typeof v === "boolean") {
      push(String(v));
    }
  };
  visit(tagsValue);
  return [...new Set(out)];
}

// src/applyTagRun.ts
async function applyTagRun(input) {
  const { vault, client, settings, targets, onProgress } = input;
  const result = {
    tagged: 0,
    chunksWritten: 0,
    skippedUnparsed: 0,
    skippedNoTags: 0,
    failed: 0,
    errors: []
  };
  const companionIndex = await buildCompanionIndex(settings, vault);
  let done = 0;
  for (const target of targets) {
    try {
      await tagOne(client, target, await resolveTags(vault, companionIndex, target), result);
    } catch (e) {
      result.failed += 1;
      result.errors.push(`${target.vaultPath}: ${e.message}`);
    }
    done += 1;
    onProgress?.(done, targets.length, target.vaultPath);
  }
  return result;
}
async function tagOne(client, target, tags, result) {
  if (tags.length === 0) {
    result.skippedNoTags += 1;
    return;
  }
  const { datasetId, documentId } = target.record;
  const status = await client.getDocumentStatus(datasetId, documentId);
  if (!status || status.run !== "DONE" || status.chunkCount === 0) {
    result.skippedUnparsed += 1;
    return;
  }
  const chunks = await client.listChunks(datasetId, documentId);
  if (chunks.length === 0) {
    result.skippedUnparsed += 1;
    return;
  }
  for (const chunk of chunks) {
    if (sameKeywords(chunk.important_keywords, tags))
      continue;
    await client.updateChunkKeywords(
      datasetId,
      documentId,
      chunk.id,
      tags,
      chunk.content
    );
    result.chunksWritten += 1;
  }
  result.tagged += 1;
}
async function resolveTags(vault, companionIndex, target) {
  const file = vault.getFile(target.vaultPath);
  if (!file)
    return [];
  if (file.extension.toLowerCase() === "md") {
    const fm = await vault.frontmatter(file);
    return noteTags(fm?.["tags"]);
  }
  const sourceFolder = target.mapping?.companionSourceFolder;
  if (!sourceFolder)
    return [];
  const companion = lookupCompanion(companionIndex, sourceFolder, file);
  return companion ? noteTags(companion["tags"]) : [];
}
function sameKeywords(a, b) {
  if (a.length !== b.length)
    return false;
  const sa = [...a].sort();
  const sb = [...b].sort();
  return sa.every((v, i) => v === sb[i]);
}

// src/vaultAccess.ts
var import_obsidian5 = require("obsidian");
var ObsidianVaultAccess = class {
  constructor(app) {
    this.app = app;
  }
  listSnapshot() {
    return this.app.vault.getFiles().map((f) => ({
      path: f.path,
      size: f.stat.size,
      mtime: f.stat.mtime
    }));
  }
  folderExists(path) {
    return this.app.vault.getAbstractFileByPath(path) !== null;
  }
  getFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    return file instanceof import_obsidian5.TFile ? file : void 0;
  }
  readBinary(path) {
    return this.app.vault.adapter.readBinary(path);
  }
  markdownFilesUnder(folder) {
    const prefix = `${folder}/`;
    return this.app.vault.getMarkdownFiles().filter((f) => f.path === folder || f.path.startsWith(prefix));
  }
  async frontmatter(file) {
    const note = this.getFile(file.path);
    if (!note)
      return void 0;
    const cached = this.app.metadataCache.getFileCache(note)?.frontmatter;
    if (cached)
      return cached;
    try {
      const text = await this.app.vault.cachedRead(note);
      const { yaml } = splitFrontmatter(text);
      if (yaml === null)
        return void 0;
      const parsed = (0, import_obsidian5.parseYaml)(yaml);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return parsed;
      }
      return void 0;
    } catch (_e) {
      return void 0;
    }
  }
  resolveLink(linkpath, sourcePath) {
    return this.app.metadataCache.getFirstLinkpathDest(linkpath, sourcePath) ?? void 0;
  }
  relatedLinks(path) {
    const resolved = this.app.metadataCache.resolvedLinks ?? {};
    const isNote = (p) => p.toLowerCase().endsWith(".md");
    const outgoing = Object.keys(resolved[path] ?? {}).filter((target) => target !== path && isNote(target)).map(noteTitle);
    const incoming = [];
    for (const [source, targets] of Object.entries(resolved)) {
      if (source !== path && isNote(source) && targets[path]) {
        incoming.push(noteTitle(source));
      }
    }
    return { outgoing, incoming };
  }
};

// src/syncEngine.ts
var SyncEngine = class {
  constructor(app, client, store, getSettings, vault = new ObsidianVaultAccess(app)) {
    this.vault = vault;
    this.client = client;
    this.store = store;
    this.getSettings = getSettings;
  }
  scope() {
    const s = this.getSettings();
    return {
      mappings: s.datasetMappings,
      extensions: s.extensions,
      excludeGlobs: s.excludeGlobs,
      processingVersion: PROCESSING_VERSION
    };
  }
  /** Obsidian adapter for the vault-snapshot seam: every file, unfiltered. */
  buildSnapshot() {
    return this.vault.listSnapshot();
  }
  async hashPath(path) {
    const bytes = await this.vault.readBinary(path);
    return sha256(bytes);
  }
  missingMappings() {
    return this.getSettings().datasetMappings.filter(
      (m) => m.vaultPath.length > 0 && !this.vault.folderExists(m.vaultPath)
    );
  }
  async computeDiff() {
    const settings = this.getSettings();
    const state = settings.state;
    const scope = this.scope();
    const stat = classifyByStat(this.buildSnapshot(), state, scope);
    const hashes = /* @__PURE__ */ new Map();
    for (const item of stat.needHash) {
      try {
        hashes.set(item.entry.path, await this.hashPath(item.entry.path));
      } catch (_e) {
      }
    }
    const hashed = finalizeWithHashes(stat.needHash, hashes);
    for (const touch of hashed.touches) {
      this.store.setFile(touch.vaultPath, {
        ...touch.record,
        size: touch.size,
        mtime: touch.mtime
      });
    }
    const changes = assembleChanges(stat, hashed);
    const snoozeHashes = await this.snoozeHashes(
      changes,
      settings.ignoredEntries
    );
    const snooze = markIgnored(changes, settings.ignoredEntries, snoozeHashes);
    for (const path of snooze.staleIgnores)
      delete settings.ignoredEntries[path];
    for (const [path, snap] of Object.entries(snooze.captured)) {
      settings.ignoredEntries[path] = snap;
    }
    await this.store.flush();
    return {
      changes: snooze.changes,
      missingMappings: this.missingMappings()
    };
  }
  /**
   * Current content hashes for ignored files whose snooze decision cannot be
   * made from stats alone.
   */
  async snoozeHashes(changes, ignoredEntries) {
    const out = /* @__PURE__ */ new Map();
    for (const change of changes) {
      const snap = ignoredEntries[change.vaultPath];
      if (!snap || change.kind === "deleted" || change.hash !== void 0) {
        continue;
      }
      const needs = "pending" in snap ? true : "deleted" in snap ? false : !(change.size === snap.size && change.mtime === snap.mtime);
      if (!needs)
        continue;
      try {
        out.set(change.vaultPath, await this.hashPath(change.vaultPath));
      } catch (_e) {
      }
    }
    return out;
  }
  /**
   * Snapshot a path for Ignore (snooze) at the moment the user ignores it:
   * `{deleted:true}` if it is gone from the vault, otherwise its current hash
   * and stats.
   */
  async snapshotForIgnore(path) {
    const file = this.vault.getFile(path);
    if (!file)
      return { deleted: true };
    const hash = await this.hashPath(path);
    return { hash, size: file.stat.size, mtime: file.stat.mtime };
  }
  async applyChanges(changes, onProgress) {
    return applySyncRun({
      vault: this.vault,
      client: this.client,
      store: this.store,
      settings: this.getSettings(),
      changes,
      onProgress,
      processingVersion: PROCESSING_VERSION
    });
  }
  /**
   * Every synced document as a tag target, paired with the mapping that owns its
   * path (needed only to find a companion note's tags for a non-markdown file).
   * This is the universe the Tags tab lists — the documents that have, or will
   * have, chunks.
   */
  tagTargets() {
    const scope = this.scope();
    return Object.entries(this.store.allFiles()).map(([vaultPath, record]) => ({
      vaultPath,
      record,
      mapping: owningMapping(vaultPath, scope)
    }));
  }
  async applyTags(targets, onProgress) {
    return applyTagRun({
      vault: this.vault,
      client: this.client,
      settings: this.getSettings(),
      targets,
      onProgress
    });
  }
};
function summarize(changes) {
  const counts = {
    new: 0,
    modified: 0,
    deleted: 0,
    unchanged: 0
  };
  for (const c of changes)
    counts[c.kind] += 1;
  return counts;
}

// src/statusView.ts
var import_obsidian6 = require("obsidian");

// src/tree.ts
function buildTree(changes) {
  const root = { name: "", path: "", children: /* @__PURE__ */ new Map() };
  for (const change of changes) {
    const parts = change.vaultPath.split("/");
    let node = root;
    let acc = "";
    parts.forEach((part, i) => {
      acc = acc ? `${acc}/${part}` : part;
      let child = node.children.get(part);
      if (!child) {
        child = { name: part, path: acc, children: /* @__PURE__ */ new Map() };
        node.children.set(part, child);
      }
      if (i === parts.length - 1)
        child.change = change;
      node = child;
    });
  }
  return root;
}
function isFileLeaf(node) {
  return !!node.change && node.children.size === 0;
}
function sortedChildren(node) {
  return [...node.children.values()].sort((a, b) => {
    const aFolder = a.children.size > 0;
    const bFolder = b.children.size > 0;
    if (aFolder !== bFolder)
      return aFolder ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
}
function leavesOf(node) {
  if (isFileLeaf(node))
    return [node];
  const out = [];
  for (const child of node.children.values())
    out.push(...leavesOf(child));
  return out;
}
function changeSummary(leaves) {
  const counts = {
    new: 0,
    modified: 0,
    deleted: 0,
    unchanged: 0
  };
  let ignored = 0;
  for (const leaf of leaves) {
    if (!leaf.change)
      continue;
    if (leaf.change.ignored)
      ignored += 1;
    else
      counts[leaf.change.kind] += 1;
  }
  const parts = [];
  if (counts.new)
    parts.push(`${counts.new} new`);
  if (counts.modified)
    parts.push(`${counts.modified} modified`);
  if (counts.deleted)
    parts.push(`${counts.deleted} deleted`);
  if (ignored)
    parts.push(`${ignored} ignored`);
  return parts.join(", ");
}
function diffVisible(changes) {
  return changes.filter((c) => c.kind !== "unchanged" && !c.ignored);
}
function addAncestorFolders(vaultPath, set) {
  const parts = vaultPath.split("/");
  let acc = "";
  for (let i = 0; i < parts.length - 1; i++) {
    acc = acc ? `${acc}/${parts[i]}` : parts[i];
    set.add(acc);
  }
}
function foldersWithChanges(changes) {
  const set = /* @__PURE__ */ new Set();
  for (const change of changes) {
    if (change.kind === "unchanged" || change.ignored)
      continue;
    addAncestorFolders(change.vaultPath, set);
  }
  return set;
}
function allFolderPaths(changes) {
  const set = /* @__PURE__ */ new Set();
  for (const change of changes)
    addAncestorFolders(change.vaultPath, set);
  return set;
}

// src/panelState.ts
function tabData(tab, changes) {
  return tab === "diff" ? diffVisible(changes) : changes.filter((c) => c.kind !== "deleted");
}
function syncAllChanges(changes) {
  return changes.filter((c) => !c.ignored && c.kind !== "unchanged");
}
function forceSelectedChanges(changes, selected) {
  return changes.filter((c) => selected.has(c.vaultPath)).map(forceUploadChange);
}
function forceAllChanges(changes) {
  return changes.filter((c) => !c.ignored).map(forceUploadChange);
}
function forceUploadChange(change) {
  return change.kind === "unchanged" || change.ignored ? {
    ...change,
    kind: "modified",
    hash: void 0,
    ...change.ignored ? { ignored: false } : {}
  } : change;
}

// src/statusView.ts
var VIEW_TYPE_RAGFLOW_SYNC = "ragflow-sync-view";
var KIND_LABEL = {
  new: "New",
  modified: "Modified",
  deleted: "Deleted",
  unchanged: "Up to date"
};
var RagflowSyncView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    /** The full diff: every in-scope file (all kinds) plus deletions. */
    this.changes = [];
    /** Tags tab universe: every synced document, with its owning mapping. */
    this.tagTargets = [];
    /** Tags tab tree data: tagTargets as badge-free leaves for the folder tree. */
    this.tagChanges = [];
    this.statusEl = null;
    this.busy = false;
    /** Which tab is showing: the Scan-diff list or the full Sync picker. */
    this.activeTab = "diff";
    /** Vault paths ticked in the current tab. Reset when the tab changes. */
    this.selected = /* @__PURE__ */ new Set();
    /** Folder paths currently expanded in the tree. */
    this.expanded = /* @__PURE__ */ new Set();
    /** Selection-dependent buttons, kept so their labels can update live. */
    this.syncSelectedBtn = null;
    this.ignoreSelectedBtn = null;
    this.applyTagsBtn = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_RAGFLOW_SYNC;
  }
  getDisplayText() {
    return "RAGFlow Sync";
  }
  getIcon() {
    return "refresh-cw";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setStatus(text) {
    if (this.statusEl)
      this.statusEl.setText(text);
  }
  async scan() {
    if (this.busy)
      return;
    if (!this.plugin.settings.apiKey) {
      new import_obsidian6.Notice("Set your RAGFlow API key in settings first.");
      return;
    }
    this.busy = true;
    this.setStatus("Scanning for differences...");
    try {
      const result = await this.plugin.engine.computeDiff();
      this.changes = result.changes;
      this.selected.clear();
      this.expanded = foldersWithChanges(this.changes);
      if (result.missingMappings.length > 0) {
        new import_obsidian6.Notice(
          `Some mapped folders were not found: ${result.missingMappings.map((m) => m.vaultPath).join(", ")}`
        );
      }
      this.render();
      const counts = summarize(this.changes);
      this.setStatus(
        `Scan complete: ${counts.new} new, ${counts.modified} modified, ${counts.deleted} deleted, ${counts.unchanged} up to date.`
      );
    } catch (e) {
      new import_obsidian6.Notice(`Scan failed: ${e.message}`);
      this.setStatus(`Scan failed: ${e.message}`);
    } finally {
      this.busy = false;
    }
  }
  /** Apply every Scan-diff-visible change that is not snoozed. */
  async syncAll() {
    await this.syncChanges(syncAllChanges(this.changes));
  }
  /**
   * Re-upload exactly the files the user ticked in the Sync tab, regardless of
   * diff result. An "unchanged" pick is promoted to "modified" (hash cleared) so
   * the upload step rebuilds RAGFlow's copy from the current source. Use to
   * rebuild specific documents — e.g. ones removed or left in a failed state on
   * the RAGFlow side — without re-uploading the rest.
   */
  async syncSelected() {
    const forced = forceSelectedChanges(this.changes, this.selected);
    if (forced.length === 0) {
      new import_obsidian6.Notice("Tick files or folders to sync.");
      return;
    }
    await this.syncChanges(forced);
  }
  /**
   * Re-upload every in-scope file regardless of diff result, by promoting
   * "unchanged" entries to "modified". Snoozed (ignored) files are left alone.
   * The command-palette "force re-sync" escape hatch; the panel offers per-file
   * selection instead.
   */
  async forceSyncAll() {
    await this.syncChanges(forceAllChanges(this.changes));
  }
  async syncChanges(changes) {
    if (this.busy)
      return;
    const actionable = changes.filter((c) => c.kind !== "unchanged");
    if (actionable.length === 0) {
      new import_obsidian6.Notice("Nothing to sync.");
      return;
    }
    this.busy = true;
    try {
      const result = await this.plugin.engine.applyChanges(
        actionable,
        (done, total, label) => {
          this.setStatus(`Syncing ${done}/${total}: ${label}`);
        }
      );
      let msg = `Synced ${result.ok} item(s).`;
      if (result.parsed > 0)
        msg += ` Parsing ${result.parsed}.`;
      if (result.failed > 0)
        msg += ` ${result.failed} failed.`;
      new import_obsidian6.Notice(msg);
      if (result.errors.length > 0) {
        console.error("RAGFlow Sync errors:", result.errors);
      }
      const uploads = actionable.filter(
        (c) => c.kind === "new" || c.kind === "modified"
      ).length;
      if (uploads > 0) {
        new import_obsidian6.Notice(
          "Re-apply tags from the Tags tab once parsing finishes."
        );
      }
    } catch (e) {
      new import_obsidian6.Notice(`Sync failed: ${e.message}`);
    } finally {
      this.busy = false;
      await this.scan();
    }
  }
  /**
   * Snooze the ticked files: snapshot each and add it to ignoredEntries so the
   * Scan diff shows it with an "Ignored" badge and "Sync all" skips it. It
   * re-surfaces on the next scan once its content drifts from the snapshot.
   */
  async ignoreSelected() {
    if (this.selected.size === 0) {
      new import_obsidian6.Notice("Tick the files you want to ignore.");
      return;
    }
    const picked = [...this.selected];
    for (const path of picked) {
      this.plugin.settings.ignoredEntries[path] = await this.plugin.engine.snapshotForIgnore(path);
    }
    await this.plugin.saveSettings();
    for (const change of this.changes) {
      if (this.selected.has(change.vaultPath))
        change.ignored = true;
    }
    this.selected.clear();
    this.render();
    new import_obsidian6.Notice(`Ignoring ${picked.length} file(s).`);
  }
  /**
   * Rebuild the Tags tab list from Synced state. Cheap (reads in-memory state),
   * so it runs on every entry to the tab to stay fresh after a sync. Each synced
   * document becomes a badge-free "unchanged" leaf for the shared folder tree.
   */
  loadTagTargets() {
    this.tagTargets = this.plugin.engine.tagTargets();
    this.tagChanges = this.tagTargets.map((t) => ({
      kind: "unchanged",
      vaultPath: t.vaultPath,
      record: t.record
    }));
    this.expanded = allFolderPaths(this.tagChanges);
  }
  /**
   * Apply each note's tags to its document's chunks. Selection-aware: ticked
   * files are tagged; with nothing ticked, every synced document is. Documents
   * not parsed yet (or notes without tags) are skipped and reported.
   */
  async applyTags() {
    if (this.busy)
      return;
    if (this.tagTargets.length === 0) {
      new import_obsidian6.Notice("Nothing synced to tag yet.");
      return;
    }
    const targets = this.selected.size > 0 ? this.tagTargets.filter((t) => this.selected.has(t.vaultPath)) : this.tagTargets;
    if (targets.length === 0) {
      new import_obsidian6.Notice("Tick files to tag, or untick all to tag everything.");
      return;
    }
    this.busy = true;
    this.setStatus(`Tagging ${targets.length} document(s)...`);
    try {
      const result = await this.plugin.engine.applyTags(
        targets,
        (done, total, label) => {
          this.setStatus(`Tagging ${done}/${total}: ${label}`);
        }
      );
      let msg = `Tagged ${result.tagged} document(s), ${result.chunksWritten} chunk(s) updated.`;
      if (result.skippedUnparsed > 0) {
        msg += ` ${result.skippedUnparsed} not parsed yet.`;
      }
      if (result.skippedNoTags > 0)
        msg += ` ${result.skippedNoTags} without tags.`;
      if (result.failed > 0)
        msg += ` ${result.failed} failed.`;
      new import_obsidian6.Notice(msg);
      this.setStatus(msg);
      if (result.errors.length > 0) {
        console.error("RAGFlow Sync tag errors:", result.errors);
      }
    } catch (e) {
      new import_obsidian6.Notice(`Tagging failed: ${e.message}`);
      this.setStatus(`Tagging failed: ${e.message}`);
    } finally {
      this.busy = false;
    }
  }
  /**
   * Switch to the Tags tab and tag every synced document. The command-palette
   * entry point; the panel button offers selection-scoped tagging instead.
   */
  async applyTagsAll() {
    this.activeTab = "tags";
    this.selected.clear();
    this.loadTagTargets();
    this.render();
    await this.applyTags();
  }
  /** The change list backing the active tab. */
  tabData() {
    return this.activeTab === "tags" ? this.tagChanges : tabData(this.activeTab, this.changes);
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ragflow-sync-view");
    this.syncSelectedBtn = null;
    this.ignoreSelectedBtn = null;
    this.applyTagsBtn = null;
    this.renderTabs(container.createDiv({ cls: "ragflow-sync-tabs" }));
    const toolbar = container.createDiv({ cls: "ragflow-sync-toolbar" });
    this.renderToolbar(toolbar);
    this.statusEl = container.createDiv({ cls: "ragflow-sync-status" });
    const data = this.tabData();
    if (data.length === 0) {
      container.createDiv({
        cls: "ragflow-sync-empty",
        text: this.emptyMessage()
      });
    } else {
      const tree = container.createDiv({ cls: "ragflow-sync-tree" });
      this.renderChildren(tree, buildTree(data), 0);
    }
    this.updateSelectionUi();
  }
  /** The empty-state line for the active tab when it has nothing to show. */
  emptyMessage() {
    if (this.activeTab === "tags") {
      return "No synced documents yet. Sync files first, then apply tags.";
    }
    if (this.changes.length === 0) {
      return 'No scan results yet. Click "Scan diff" to compare your vault with RAGFlow.';
    }
    return this.activeTab === "diff" ? "Everything is up to date." : "No in-scope files to show.";
  }
  /** The Scan diff / Sync / Tags segmented toggle. */
  renderTabs(bar) {
    const tab = (id, label) => {
      const btn = bar.createEl("button", { text: label });
      btn.toggleClass("mod-cta", this.activeTab === id);
      btn.onclick = () => {
        if (this.activeTab === id)
          return;
        this.activeTab = id;
        this.selected.clear();
        if (id === "tags")
          this.loadTagTargets();
        this.render();
        if (id === "sync" && this.changes.length === 0)
          void this.scan();
      };
    };
    tab("diff", "Scan diff");
    tab("sync", "Sync");
    tab("tags", "Tags");
  }
  renderToolbar(toolbar) {
    if (this.activeTab === "diff") {
      const scanBtn = toolbar.createEl("button", { text: "Scan diff" });
      scanBtn.onclick = () => void this.scan();
      const syncAllBtn = toolbar.createEl("button", { text: "Sync all" });
      syncAllBtn.addClass("mod-cta");
      syncAllBtn.onclick = () => void this.syncAll();
      this.ignoreSelectedBtn = toolbar.createEl("button", {
        text: "Ignore selected"
      });
      this.ignoreSelectedBtn.onclick = () => void this.ignoreSelected();
    } else if (this.activeTab === "sync") {
      this.syncSelectedBtn = toolbar.createEl("button", {
        text: "Sync selected"
      });
      this.syncSelectedBtn.addClass("mod-cta");
      this.syncSelectedBtn.onclick = () => void this.syncSelected();
    } else {
      this.applyTagsBtn = toolbar.createEl("button", {
        text: "Apply tags"
      });
      this.applyTagsBtn.addClass("mod-cta");
      this.applyTagsBtn.onclick = () => void this.applyTags();
    }
  }
  /** Render the folders-then-files under a node, sorted, at the given depth. */
  renderChildren(parent, node, depth) {
    for (const child of sortedChildren(node)) {
      if (isFileLeaf(child))
        this.renderFile(parent, child, depth);
      else
        this.renderFolder(parent, child, depth);
    }
  }
  renderFolder(parent, node, depth) {
    const leaves = leavesOf(node);
    const expanded = this.expanded.has(node.path);
    const row = parent.createDiv({ cls: "ragflow-tree-row ragflow-tree-folder" });
    row.style.paddingLeft = `${depth * 16}px`;
    const twisty = row.createSpan({
      cls: "ragflow-tree-twisty",
      text: expanded ? "\u25BE" : "\u25B8"
    });
    twisty.onclick = (e) => {
      e.stopPropagation();
      this.toggleFolder(node.path);
    };
    const box = row.createEl("input", { type: "checkbox" });
    const picked = leaves.filter((l) => this.selected.has(l.path)).length;
    box.checked = picked > 0 && picked === leaves.length;
    box.indeterminate = picked > 0 && picked < leaves.length;
    box.onclick = (e) => e.stopPropagation();
    box.onchange = () => {
      for (const leaf of leaves) {
        if (box.checked)
          this.selected.add(leaf.path);
        else
          this.selected.delete(leaf.path);
      }
      this.render();
    };
    const label = row.createDiv({ cls: "ragflow-tree-name" });
    label.setText(node.name);
    label.onclick = () => this.toggleFolder(node.path);
    if (this.activeTab === "diff") {
      const summary = changeSummary(leaves);
      if (summary) {
        row.createSpan({ cls: "ragflow-tree-count", text: summary });
      }
    }
    if (expanded) {
      const childWrap = parent.createDiv({ cls: "ragflow-tree-children" });
      this.renderChildren(childWrap, node, depth + 1);
    }
  }
  renderFile(parent, node, depth) {
    const change = node.change;
    const row = parent.createDiv({ cls: "ragflow-tree-row ragflow-tree-file" });
    row.style.paddingLeft = `${depth * 16 + 16}px`;
    const box = row.createEl("input", { type: "checkbox" });
    box.checked = this.selected.has(change.vaultPath);
    box.onchange = () => {
      if (box.checked)
        this.selected.add(change.vaultPath);
      else
        this.selected.delete(change.vaultPath);
      this.render();
    };
    row.createDiv({ cls: "ragflow-tree-name", text: node.name });
    if (this.activeTab === "diff") {
      row.createSpan({
        cls: `ragflow-sync-badge ${change.kind}`,
        text: KIND_LABEL[change.kind]
      });
    }
  }
  toggleFolder(path) {
    if (this.expanded.has(path))
      this.expanded.delete(path);
    else
      this.expanded.add(path);
    this.render();
  }
  /** Reflect the current tick count on the selection-dependent buttons. */
  updateSelectionUi() {
    const n = this.selected.size;
    if (this.syncSelectedBtn) {
      this.syncSelectedBtn.setText(
        n > 0 ? `Sync selected (${n})` : "Sync selected"
      );
      this.syncSelectedBtn.toggleClass("mod-warning", n > 0);
    }
    if (this.ignoreSelectedBtn) {
      this.ignoreSelectedBtn.setText(
        n > 0 ? `Ignore selected (${n})` : "Ignore selected"
      );
      this.ignoreSelectedBtn.disabled = n === 0;
    }
    if (this.applyTagsBtn) {
      this.applyTagsBtn.setText(
        n > 0 ? `Apply tags (${n})` : "Apply tags (all)"
      );
    }
  }
};

// src/main.ts
var RagflowSyncPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.client = new RagflowClient(() => this.settings);
    this.store = new SyncStateStore(
      this.settings.state,
      () => this.saveSettings()
    );
    this.engine = new SyncEngine(
      this.app,
      this.client,
      this.store,
      () => this.settings
    );
    this.registerView(
      VIEW_TYPE_RAGFLOW_SYNC,
      (leaf) => new RagflowSyncView(leaf, this)
    );
    this.addRibbonIcon("refresh-cw", "RAGFlow Sync", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-ragflow-sync-panel",
      name: "Open sync panel",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "ragflow-scan-diff",
      name: "Scan for differences",
      callback: async () => {
        const view = await this.activateView();
        await view?.scan();
      }
    });
    this.addCommand({
      id: "ragflow-sync-all",
      name: "Sync all changes",
      callback: async () => {
        const view = await this.activateView();
        if (!view)
          return;
        await view.scan();
        await view.syncAll();
      }
    });
    this.addCommand({
      id: "ragflow-force-resync",
      name: "Force re-sync all (re-upload everything)",
      callback: async () => {
        const view = await this.activateView();
        if (!view)
          return;
        await view.scan();
        await view.forceSyncAll();
      }
    });
    this.addCommand({
      id: "ragflow-apply-tags",
      name: "Apply tags to chunks",
      callback: async () => {
        const view = await this.activateView();
        if (!view)
          return;
        await view.applyTagsAll();
      }
    });
    this.addSettingTab(new RagflowSyncSettingTab(this.app, this));
  }
  onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_RAGFLOW_SYNC)[0] ?? null;
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_RAGFLOW_SYNC,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      return leaf.view;
    }
    new import_obsidian7.Notice("Could not open RAGFlow Sync panel.");
    return null;
  }
  async loadSettings() {
    const data = await this.loadData() ?? {};
    this.settings = normalizeSettings(data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
